import test from 'node:test';import assert from 'node:assert/strict';import {fresh,restore,move,act,choose,fight,trade,talk,KEY} from '../county/engine.js';import {places,resources,nodeDefs,items} from '../county/content.js';import {advance} from '../county/world.js';import {command} from '../county/commands.js';import {save,load,importSave} from '../county/storage.js';
const copy=s=>assert.deepEqual(restore(JSON.stringify(s)),s);
test('县境16处地图互通，普通人实际走访全部地点，雨天改变路程但所有移动零精力',()=>{assert.equal(Object.keys(places).length,16);for(const [key,p] of Object.entries(places))for(const to of p.routes)assert.ok(places[to].routes.includes(key));const s=fresh(),seen=new Set([s.place]);function visit(key){for(const to of places[key].routes)if(!seen.has(to)){assert.ok(move(s,to,()=>1));seen.add(to);visit(to);assert.ok(move(s,key,()=>1));}}visit('county');assert.equal(seen.size,16);assert.equal(s.energy,100);assert.equal(s.coins,30);assert.equal(move(s,'mine'),false);s.weather='雨';const start=s.minute;move(s,'village');assert.equal(s.minute,start+45);copy(s);});
test('各地资源、工具、精力与伤势门槛真实；失败仍耗时间尝试次数并结算相关成长',()=>{const s=fresh();s.place='dock';assert.equal(act(s,'fish'),false);s.bag.rod=1;assert.ok(act(s,'fish',()=>1));assert.equal(s.bag.fish,0);assert.equal(s.skills.fish,1);assert.equal(s.energy,86);assert.equal(s.minute,570);assert.equal(s.nodes['dock:fish'].left,2);assert.match(s.result.join(' '),/钓鱼 Lv1：0\/100 → 1\/100（\+1）/);s.hp=24;assert.equal(act(s,'fish'),false);assert.equal(s.energy,86);s.hp=100;s.energy=0;assert.equal(act(s,'fish'),false);copy(s);});
test('有限资源尝试不因重进或读档刷新，世界跨两日才恢复，菜单数据来自实际状态',()=>{const s=fresh();s.place='foot';for(let i=0;i<3;i++)act(s,'wood',()=>0);assert.equal(s.bag.wood,6);assert.equal(act(s,'wood'),false);move(s,'village');move(s,'foot');assert.equal(s.nodes['foot:wood'].left,0);copy(s);advance(s,1440);assert.equal(s.day,2);assert.equal(s.nodes['foot:wood'].left,0);advance(s,1440);assert.equal(s.day,3);assert.equal(s.nodes['foot:wood'].left,3);assert.equal(s.nodes['foot:wood'].refreshDay,5);assert.ok(s.news.some(x=>x.includes('世界新闻')));copy(s);});
test('危险采集明确确认，退出不付代价；成功与受伤真实，低气血不会被强行杀死',()=>{const s=fresh();s.place='mine';s.bag.pick=1;assert.ok(act(s,'ore'));assert.equal(s.pending.type,'resource');assert.equal(s.energy,100);assert.equal(s.minute,480);copy(s);choose(s,'leave');assert.equal(s.nodes['mine:ore'].left,3);act(s,'ore');choose(s,'gather',()=>0);assert.equal(s.bag.ore,2);assert.equal(s.hp,92);assert.equal(s.energy,80);assert.equal(s.skills.mining,2);assert.equal(s.bag.pick,1);copy(s);});
test('捕鱼出售、药材治疗、矿石加工三条闭环守恒，生产记录消耗及剩余材料',()=>{const s=fresh();s.place='market';trade(s,'buy','rod');assert.equal(s.coins,24);s.place='dock';act(s,'fish',()=>0);s.place='market';trade(s,'sell','fish');assert.equal(s.coins,29);assert.equal(s.bag.fish,0);s.place='village';act(s,'herb',()=>0);s.hp=60;act(s,'heal');assert.equal(s.hp,80);assert.equal(s.bag.herb,0);s.place='market';trade(s,'buy','pick');s.place='mine';act(s,'ore');choose(s,'gather',()=>0);s.place='foot';act(s,'wood',()=>0);s.place='workshop';s.minute=480;act(s,'smelt');assert.equal(s.bag.ore,0);assert.equal(s.bag.wood,1);assert.equal(s.bag.iron,1);assert.match(s.result.join(' '),/本次生产：铁料×1.*材料消耗：铁矿石 -2、木料 -1.*当前库存：铁矿石 0、木料 1/);copy(s);});
test('生活恢复、工作时间与交易边界不凭空赚钱，村里零钱也能睡觉',()=>{const s=fresh();assert.equal(act(s,'sleep'),false);act(s,'work');assert.equal(s.coins,42);assert.equal(s.energy,76);s.minute=1000;assert.equal(act(s,'work'),false);s.place='market';s.minute=1186;assert.equal(trade(s,'buy','grain'),false);s.minute=1185;assert.ok(trade(s,'buy','grain'));assert.equal(s.minute,1200);assert.equal(trade(s,'buy','grain'),false);s.place='village';s.coins=0;s.hp=60;act(s,'sleep');assert.equal(s.hp,80);assert.equal(s.energy,100);assert.equal(s.coins,0);copy(s);});
test('真实交手可绕开、低精力撤离、获胜或死亡，死亡阻止继续行动并保存',()=>{const s=fresh();s.place='hill';move(s,'oldroad',()=>0);copy(s);choose(s,'avoid');assert.equal(s.combat,null);s.encounterDay=0;s.place='hill';move(s,'oldroad',()=>0);choose(s,'fight');s.energy=0;fight(s,'flee');assert.equal(s.combat,null);s.encounterDay=0;s.place='hill';s.energy=100;move(s,'oldroad',()=>0);choose(s,'fight');s.hp=6;fight(s,'attack');assert.equal(s.dead,true);assert.equal(s.hp,0);assert.equal(move(s,'hill'),false);copy(s);const win=fresh();win.place='hill';move(win,'oldroad',()=>0);choose(win,'fight');for(let i=0;i<3;i++)fight(win,'heavy',()=>0);assert.equal(win.coins,34);assert.equal(win.combat,null);copy(win);});
test('普通天赋、疲劳与满技能结算克制，NPC按作息出现且关系不重复领取',()=>{const s=fresh({talent:'enduring'});act(s,'work');assert.equal(s.energy,78);s.place='foot';s.energy=20;act(s,'wood',()=>0);assert.equal(s.energy,10);assert.equal(s.skills.forage,1);s.energy=100;s.skills.forage=2100;act(s,'wood',()=>0);assert.equal(s.skills.forage,2100);s.place='market';s.minute=480;talk(s,'merchant');talk(s,'merchant');assert.equal(s.relations.merchant,1);s.minute=1300;assert.equal(talk(s,'merchant'),false);copy(s);});
test('独立存档、损坏验证与导入失败保留当前进度，拒绝死亡读档复活',()=>{const s=fresh(),records=new Map(),storage={getItem:k=>records.get(k)||null,setItem:(k,v)=>records.set(k,v)};save(s,storage);assert.equal(KEY,'jianghu-qinghe-county-v1');assert.deepEqual(load(storage),s);for(const change of [b=>b.bag.ore=-1,b=>b.nodes['mine:ore'].left=20,b=>b.nodes['foot:wood'].refreshDay=1,b=>b.place='unknown',b=>b.pending={type:'resource',key:'wood'},b=>b.combat={hp:30},b=>b.coins=NaN]){const b=structuredClone(s);change(b);assert.throws(()=>restore(JSON.stringify(b)));}const full={getItem:storage.getItem,setItem:()=>{throw Error('full');}};assert.throws(()=>importSave(JSON.stringify(fresh({name:'其他'})),s,full));assert.deepEqual(load(storage),s);assert.throws(()=>restore(JSON.stringify({version:1})));const dead=fresh();dead.dead=true;dead.hp=0;assert.throws(()=>importSave(JSON.stringify(s),dead,storage),/恢复/);});
test('自由输入真实执行，食物加工无行动ID冲突，全年推进资源与记录有界',()=>{const s=fresh();assert.ok(command(s,'去河湾村'));assert.ok(command(s,'采药'));assert.equal(command(s,'去旧矿洞'),false);s.place='workshop';s.bag.vegetable=1;s.bag.grain=1;s.bag.wood=1;s.minute=480;assert.ok(command(s,'做菜饭'));assert.equal(s.bag.food,5);assert.equal(s.bag.vegetable,0);advance(s,365*1440);assert.ok(s.news.length<=20);assert.equal(Object.keys(s.nodes).length,Object.keys(nodeDefs).length);copy(s);});

test('农户、医者和武馆不能闭门工作，诊治与练习需留足完成时间',()=>{const s=fresh();s.place='fields';s.minute=1100;assert.equal(act(s,'vegetables'),false);s.place='inn';s.hp=50;assert.equal(act(s,'doctor'),false);s.place='village';s.minute=1021;assert.equal(act(s,'doctor'),false);s.minute=1020;assert.ok(act(s,'doctor'));assert.equal(s.minute,1080);s.place='school';s.minute=961;assert.equal(act(s,'train'),false);s.minute=960;assert.ok(act(s,'train'));assert.equal(s.minute,1080);copy(s);});
