import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,act,trade,restore,acceptJob} from '../src/rebuild/engine.js';
import {command} from '../src/rebuild/commands.js';
test('拾柴成功才给材料，失败有相关练习，材料不凭空增加',()=>{const s=fresh();s.place='bamboo';act(s,'collectWood',()=>0);assert.equal(s.bag.wood,2);assert.equal(s.skills.forage,2);assert.equal(s.energy,88);assert.equal(s.minute,600);act(s,'collectWood',()=>1);assert.equal(s.bag.wood,2);assert.equal(s.skills.forage,4);assert.equal(s.skills.forge,0);assert.match(s.result.join(' '),/没有合用/)});
test('采矿需工具、正确地点和体力；缺条件不耗时不造矿石',()=>{const s=fresh();assert.equal(act(s,'mine'),false);s.place='hill';assert.equal(act(s,'mine'),false);assert.equal(s.minute,480);s.bag.tool=1;s.energy=19;assert.equal(act(s,'mine'),false);assert.equal(s.energy,19);s.energy=100;act(s,'mine',()=>0);assert.equal(s.bag.ore,1);assert.equal(s.bag.iron,0);assert.equal(s.bag.tool,1);assert.equal(s.skills.mining,2);assert.equal(s.skills.forge,0);assert.equal(s.energy,80);s.hp=24;assert.equal(act(s,'mine'),false);assert.equal(s.bag.ore,1)});
test('疲劳降低采集机会与成长；失败没有材料，满额不增加',()=>{const s=fresh();s.place='hill';s.bag.tool=1;s.energy=20;act(s,'mine',()=>0.6);assert.equal(s.bag.ore,0);assert.equal(s.skills.mining,1);assert.equal(s.energy,0);s.place='bamboo';s.energy=100;s.skills.forage=2100;act(s,'collectWood',()=>0);assert.equal(s.skills.forage,2100);assert.ok(!s.result.some(x=>x.startsWith('采集 Lv')))});
test('从购买工具、自产原料、炼铁到打造交付真实闭环，不耗用采矿工具',()=>{const s=fresh();trade(s,'buy','tool');assert.equal(s.coins,10);s.place='hill';act(s,'mine',()=>0);act(s,'mine',()=>0);s.place='bamboo';act(s,'collectWood',()=>0);act(s,'collectWood',()=>0);s.place='forge';act(s,'rest');act(s,'smelt',()=>0);assert.equal(s.bag.ore,0);assert.equal(s.bag.wood,2);assert.equal(s.bag.iron,2);assert.ok(s.result.includes('材料消耗：铁矿石 -2、木料 -2'));act(s,'forge',()=>0);assert.equal(s.bag.tool,2);assert.equal(s.bag.iron,0);assert.equal(s.bag.wood,1);assert.equal(s.skills.forage,4);assert.equal(s.skills.mining,4);assert.equal(s.skills.forge,4);acceptJob(s,'tools');act(s,'deliver');assert.equal(s.bag.tool,1);assert.equal(s.coins,32);assert.equal(s.skills.trade,1);assert.deepEqual(restore(JSON.stringify(s)),s)});
test('炼铁缺料与疲劳失误仍精确记录消耗和库存',()=>{const s=fresh();s.place='forge';s.bag.ore=2;assert.equal(act(s,'smelt'),false);assert.equal(s.bag.ore,2);assert.equal(s.minute,480);s.bag.wood=2;s.energy=18;act(s,'smelt',()=>0);assert.equal(s.bag.ore,0);assert.equal(s.bag.wood,0);assert.equal(s.bag.iron,0);assert.equal(s.skills.forge,1);assert.match(s.result.join(' '),/当前库存：铁矿石 0、木料 0、铁料 0/)});
test('原存档补零保留历史账目，异常采集数值被拒绝，自由输入使用实装行动',()=>{const s=fresh();delete s.skills.forage;delete s.skills.mining;delete s.bag.ore;s.bag.wood=7;s.skills.forge=15;const migrated=restore(JSON.stringify(s));assert.equal(migrated.bag.wood,7);assert.equal(migrated.skills.forge,15);assert.equal(migrated.bag.ore,0);assert.equal(migrated.skills.mining,0);assert.throws(()=>restore(JSON.stringify({...fresh(),skills:{...fresh().skills,mining:-1}})));migrated.place='bamboo';assert.equal(command(migrated,'我拾柴'),true);assert.equal(migrated.skills.forage,2);migrated.place='hill';assert.equal(command(migrated,'采矿'),false)});
