import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,act,choose,restore,travel} from '../src/rebuild/engine.js';
import {sites,siteBlocker} from '../src/rebuild/sites.js';
const saved=s=>restore(JSON.stringify(s));
const enter=place=>{const s=fresh();s.place=place;assert.ok(act(s,'surveySite'));return s;};
test('三个固定旧址寻访耗时耗精力、没有自动奖励；记录和选择跨存档保留',()=>{for(const [key,def] of Object.entries(sites)){const s=enter(def.place);assert.equal(s.pending.key,key);assert.equal(s.minute,540);assert.equal(s.energy,96);assert.equal(s.coins,30);assert.deepEqual(saved(s),s);assert.ok(Object.values(s.skills).every(v=>v===0));assert.equal(travel(s,'town'),false);choose(s,'leave');const before=s.minute;assert.ok(act(s,'visitSite'));assert.equal(s.minute,before);assert.equal(s.energy,96);assert.equal(s.sites[key].day,1);}});
test('浅采与深入互斥，材料有限，工具保留、只涨采矿；跨日再访不刷新',()=>{const s=enter('hill');assert.equal(choose(s,'extract'),false);assert.equal(s.energy,96);s.bag.tool=1;assert.ok(choose(s,'extract'));assert.equal(s.bag.ore,2);assert.equal(s.bag.tool,1);assert.equal(s.skills.mining,1);assert.equal(s.skills.forge,0);act(s,'visitSite');const before=structuredClone(s);assert.equal(choose(s,'deep'),false);assert.equal(s.minute,before.minute);assert.equal(s.energy,before.energy);choose(s,'leave');s.day=4;act(s,'visitSite');assert.equal(choose(s,'extract'),false);assert.equal(s.bag.ore,2);assert.ok(saved(s));});
test('深入风险明示，低气血和疲劳整项阻止；风险只造成可恢复伤势',()=>{const s=enter('hill');s.bag.tool=1;s.hp=49;assert.equal(choose(s,'deep'),false);s.hp=50;s.energy=39;assert.equal(choose(s,'deep'),false);assert.equal(s.bag.ore,0);s.energy=40;assert.ok(choose(s,'deep',()=>0));assert.equal(s.hp,38);assert.equal(s.dead,false);assert.equal(s.energy,20);assert.equal(s.bag.ore,3);assert.equal(s.skills.mining,2);assert.match(s.result.join(' '),/气血：50 → 38/);assert.match(s.result.join(' '),/采矿 Lv1：0\/100 → 2\/100/);assert.ok(saved(s));});
test('营地搜索空手也消耗真实时间和精力，不可重抽；木料可以另行整理',()=>{const s=enter('bamboo');const before=s.minute;choose(s,'search',()=>0.9);assert.equal(s.bag.food,2);assert.equal(s.minute,before+60);assert.equal(s.energy,88);assert.equal(s.skills.forage,1);act(s,'visitSite');assert.equal(choose(s,'search',()=>0),false);assert.ok(choose(s,'wood'));assert.equal(s.bag.wood,2);assert.equal(s.skills.forage,2);assert.equal(s.skills.woodwork,0);act(s,'visitSite');assert.ok(sites.camp.choices.every(c=>siteBlocker(s,'camp',c)));choose(s,'leave');assert.ok(saved(s));});
test('栈道清理实际劳动后发报酬，遗物另行查找；不增加无关武学经验',()=>{const s=enter('ferry');assert.ok(choose(s,'clear'));assert.equal(s.coins,42);assert.equal(s.energy,80);assert.equal(s.skills.carry,1);assert.equal(s.skills.trade,0);act(s,'visitSite');assert.ok(choose(s,'search',()=>0));assert.equal(s.bag.wood,1);assert.equal(s.energy,72);assert.equal(s.skills.forage,1);assert.equal(s.place,'ferry');assert.ok(saved(s));});
test('旧石棚与新采石场共用矿料记录；旧存档兼容、伪造位置和重复记录被拒绝',()=>{const s=fresh();s.place='hill';s.bag.tool=1;act(s,'explore',()=>.36);choose(s,'extract');assert.deepEqual(s.sites.quarry.done,['ore']);act(s,'visitSite');assert.equal(choose(s,'deep'),false);choose(s,'leave');s.day++;act(s,'explore',()=>.36);assert.equal(choose(s,'extract'),false);assert.equal(s.bag.ore,2);const old=fresh();delete old.sites;assert.deepEqual(saved(old).sites,{});for(const record of [{quarry:{day:2,done:[]}},{toString:{day:1,done:[]}},{camp:{day:1,done:['search','search']}},{camp:{day:1,done:['ore']}}]){const bad=fresh();bad.sites=record;assert.throws(()=>saved(bad));}const wrong=enter('hill');wrong.place='town';assert.throws(()=>saved(wrong));});

import {command} from '../src/rebuild/commands.js';
test('自由输入可以寻找和再访旧址，其他地点不能凭空进入',()=>{const s=fresh();assert.equal(command(s,'寻找旧址'),false);s.place='ferry';assert.ok(command(s,'寻找旧址'));choose(s,'leave');assert.ok(command(s,'再访旧址'));assert.equal(s.pending.key,'riverside');});
