import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import vm from 'node:vm';
import {setupOffline} from '../src/rebuild/offline.js';
const version=JSON.parse(readFileSync(new URL('../package.json',import.meta.url),'utf8')).version;
const source=readFileSync(new URL('../sw.js',import.meta.url),'utf8');
function worker({online=true,failPath=''}={}){
 const handlers={},overrides=new Map(),store=new Map(),prefix='jianghu-wanxiang-offline:/jianghu/:',current=prefix+version;let skipped=0,claimed=0;
 const net=async request=>{const url=new URL(typeof request==='string'?request:request.url);if(!online||url.pathname.endsWith(failPath)&&failPath)throw Error('offline');const path=url.pathname.replace('/jianghu/','');if(overrides.has(path))return new Response(overrides.get(path));return new Response(readFileSync(new URL('../'+path,import.meta.url),'utf8'))};
 const cacheFor=name=>{if(!store.has(name))store.set(name,new Map());return {addAll:async requests=>{const values=await Promise.all(requests.map(async x=>[x.url,await net(x)]));for(const [key,r] of values)store.get(name).set(key,r)},match:async url=>store.get(name).get(url)?.clone()}};
 const self={registration:{scope:'https://game.test/jianghu/'},addEventListener:(name,fn)=>handlers[name]=fn,skipWaiting:async()=>skipped++,clients:{claim:async()=>claimed++}};
 vm.runInNewContext(source,{self,URL,Request,Response,caches:{open:async name=>cacheFor(name),keys:async()=>[...store.keys()],delete:async name=>store.delete(name)},fetch:net});
 const lifecycle=async name=>{let p;handlers[name]({waitUntil:x=>p=x});await p};
 const request=async(path,method='GET')=>{let p;handlers.fetch({request:new Request('https://game.test'+path,{method}),respondWith:x=>p=x});return p?await p:null};
 return {store,current,handlers,lifecycle,request,setResponse:(path,text)=>overrides.set(path,text),setOffline:()=>online=false,skipped:()=>skipped,claimed:()=>claimed};
}
test('完整预缓存后断网可加载页面和全部模块，游戏版本参数不阻碍离线',async()=>{const w=worker();await w.lifecycle('install');assert.equal(w.skipped(),1);w.setOffline();for(const path of ['/jianghu/?v=1.0.9','/jianghu/index.html?from=home','/jianghu/src/rebuild/engine.js?v=1.0.9','/jianghu/src/rebuild/planner.js?v=1.0.9']){const r=await w.request(path.replace('1.0.9',version));assert.equal(r.status,200);assert.ok((await r.text()).length>100)}const manifest=await w.request('/jianghu/manifest.webmanifest');assert.equal((await manifest.json()).display,'standalone')});
test('漏文件或断网安装不能启用半成品离线壳',async()=>{const w=worker({failPath:'content.js'});await assert.rejects(w.lifecycle('install'));assert.equal(w.skipped(),0);assert.equal(w.store.get(w.current).size,0);const offline=worker({online:false});await assert.rejects(offline.lifecycle('install'));assert.equal(offline.skipped(),0)});
test('升级只清理当前游戏旧缓存，不触及其他项目、存档和请求',async()=>{const w=worker();w.store.set('jianghu-wanxiang-offline:/jianghu/:1.0.8',new Map());w.store.set('jianghu-wanxiang-offline:/other/:1.0.8',new Map());w.store.set('other-cache',new Map());await w.lifecycle('install');await w.lifecycle('activate');assert.equal(w.store.has('jianghu-wanxiang-offline:/jianghu/:1.0.8'),false);assert.equal(w.store.has('jianghu-wanxiang-offline:/other/:1.0.8'),true);assert.equal(w.store.has('other-cache'),true);assert.equal(w.claimed(),1);assert.equal(await w.request('/jianghu/legacy.html'),null);assert.equal(await w.request('/elsewhere/'),null);assert.equal(await w.request('/jianghu/index.html','POST'),null)});
test('离线文件缺失有明确错误，不伪造可玩页面',async()=>{const w=worker({online:false});const r=await w.request('/jianghu/');assert.equal(r.status,503);assert.match(await r.text(),/尚未准备完成/)});
test('离线清单覆盖真实模块及依赖，Pages发布包括离线入口，版本一致',async()=>{const w=worker();await w.lifecycle('install');const cached=[...w.store.get(w.current).keys()];const modulePaths=cached.filter(x=>x.endsWith('.js?v='+version)).map(x=>new URL(x).pathname.replace('/jianghu/',''));for(const p of modulePaths){assert.ok(existsSync(new URL('../'+p,import.meta.url)));const text=readFileSync(new URL('../'+p,import.meta.url),'utf8');for(const match of text.matchAll(/from '\.\/(.+?)'/g)){const absolute=new URL(match[1],'https://game.test/jianghu/'+p).href;assert.ok(cached.includes(absolute),'uncached import '+absolute)}}const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');assert.ok(html.includes('app.js?v='+version));assert.match(html,/rel="manifest"/);const workflow=readFileSync(new URL('../.github/workflows/pages.yml',import.meta.url),'utf8');assert.match(workflow,/sw.js manifest.webmanifest _site/)});
test('不支持离线与注册失败时诚实提示，不阻碍游戏；准备后支持更新',async()=>{const status={textContent:''},button={};await setupOffline({nav:{},status,button});assert.match(status.textContent,/未提供/);assert.equal(button.disabled,true);await setupOffline({nav:{serviceWorker:{register:async()=>{throw Error('blocked')}}},status,button,base:'https://game.test/jianghu/'});assert.match(status.textContent,/准备失败/);const registration={active:{},addEventListener(){},update:async()=>{}};let requested;await setupOffline({nav:{serviceWorker:{ready:Promise.resolve(registration),register:async(...args)=>{requested=args;return registration}}},status,button,base:'https://game.test/jianghu/?v='+version});assert.equal(requested[0],'https://game.test/jianghu/sw.js');assert.equal(requested[1].scope,'https://game.test/jianghu/');assert.equal(button.disabled,false);assert.match(status.textContent,/已就绪/);await button.onclick();assert.match(status.textContent,/检查已完成/);registration.update=async()=>{throw Error('offline')};await button.onclick();assert.match(status.textContent,/无法检查更新/);assert.equal(button.disabled,false)});

test('联网优先取新版页面，未知版本模块不冒充缓存，断网仍能读取完整当前版',async()=>{const w=worker();await w.lifecycle('install');w.setResponse('index.html','新版页面');w.setResponse('src/rebuild/app.js','新版模块');assert.equal(await (await w.request('/jianghu/index.html')).text(),'新版页面');assert.equal(await (await w.request('/jianghu/src/rebuild/app.js?v=future')).text(),'新版模块');w.setOffline();assert.equal((await w.request('/jianghu/src/rebuild/app.js?v=future')).status,503);const cached=await w.request('/jianghu/');assert.equal(cached.status,200);assert.match(await cached.text(),/江湖：万象/);assert.match(await (await w.request('/jianghu/src/rebuild/app.js?v='+version)).text(),/setupOffline/)});
