import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,acceptJob,travel,choose,act,restore} from '../src/rebuild/engine.js';
import {advance,encounter} from '../src/rebuild/world.js';import {jobDeliveryBlocker,jobDestination} from '../src/rebuild/contracts.js';import {jobs} from '../src/rebuild/content.js';
const begin=id=>{const s=fresh();assert.ok(acceptJob(s,id));return s;};
const roundtrip=s=>assert.deepEqual(restore(JSON.stringify(s)),s);
test('失物成功归还才领奖，普通物品稀有奖励与经验真实，不能重复搜寻或交还',()=>{const s=begin('lostPouch');assert.equal(act(s,'deliver'),false);assert.match(jobDeliveryBlocker(s,jobs.lostPouch),/逐步/);assert.equal(jobDestination(s),'road');travel(s,'road');roundtrip(s);choose(s,'clue');assert.equal(s.job.phase,1);assert.equal(s.coins,30);travel(s,'bamboo');choose(s,'search',()=>.2);assert.equal(s.job.phase,2);assert.equal(s.skills.forage,1);assert.match(s.result.join(' '),/采集 Lv1：0\/100 → 1\/100（\+1）/);assert.equal(choose(s,'search'),false);travel(s,'road');travel(s,'town');roundtrip(s);choose(s,'return',()=>.1);assert.equal(s.coins,54);assert.equal(s.bag.food,3);assert.equal(s.relations.merchant,2);assert.equal(s.energy,87);assert.equal(s.skills.trade,0);assert.equal(s.job,null);assert.equal(choose(s,'return'),false);assert.equal(acceptJob(s,'lostPouch'),false);roundtrip(s);});
test('失物失败、无额外赠物与退出均无虚构收益，搜索只结算一次',()=>{const s=begin('lostPouch');travel(s,'road');choose(s,'clue');travel(s,'bamboo');choose(s,'search',()=>.9);assert.equal(s.job.phase,3);travel(s,'road');travel(s,'town');choose(s,'report');assert.equal(s.coins,36);assert.equal(s.bag.food,2);assert.equal(s.relations.merchant,1);assert.equal(s.skills.forage,1);const a=begin('lostPouch');travel(a,'road');choose(a,'leave');assert.equal(a.coins,30);assert.equal(a.energy,100);assert.equal(a.jobsDone.lostPouch,undefined);roundtrip(a);});
test('采药护送绕行、陡坡风险与提前撤回不同，移动一律零精力且无伪造采药战斗经验',()=>{for(const [choice,pay,herb,hp,en,xp] of [['bypass',20,1,100,98,2],['protect',28,2,92,86,2],['retreat',6,0,100,98,0]]){const s=begin('herbalEscort');travel(s,'village');travel(s,'hill');assert.equal(s.energy,100);choose(s,choice,()=>.1);assert.equal(s.coins,30);assert.equal(s.bag.herb,0);assert.equal(s.hp,hp);roundtrip(s);const energy=s.energy;travel(s,'village');assert.equal(s.energy,energy);choose(s,choice==='retreat'?'report':'finish');assert.equal(s.coins,30+pay);assert.equal(s.bag.herb,herb);assert.equal(s.energy,en);assert.equal(s.skills.escort,xp);assert.equal(s.skills.herb,0);assert.equal(s.skills.battle,0);assert.equal(s.job,null);roundtrip(s);}});
test('采药受伤与疲劳门槛不扣资源；奖励封顶、不重复领奖',()=>{const s=begin('herbalEscort');travel(s,'village');travel(s,'hill');s.hp=49;assert.equal(choose(s,'protect'),false);assert.equal(s.energy,100);s.hp=50;s.energy=11;assert.equal(choose(s,'protect'),false);choose(s,'bypass');travel(s,'village');s.relations.doctor=99;s.skills.escort=2100;choose(s,'finish');assert.equal(s.relations.doctor,100);assert.equal(s.skills.escort,2100);assert.equal(choose(s,'finish'),false);assert.equal(s.coins,50);roundtrip(s);});
test('调解必须先听双方，直接协商与证词路线各自结算，不能跳步骤刷经验',()=>{for(const witness of [false,true]){const s=begin('neighbourDispute');travel(s,'dock');assert.equal(choose(s,'mediate'),false);choose(s,'listen');assert.equal(s.pending.type,'errand');roundtrip(s);if(witness){choose(s,'witness');assert.equal(jobDestination(s),'town');travel(s,'town');choose(s,'testimony');assert.equal(s.skills.trade,1);roundtrip(s);travel(s,'dock');choose(s,'mediate');}else choose(s,'settle');assert.equal(s.coins,witness?48:40);assert.equal(s.relations.porter,witness?3:1);assert.equal(s.skills.trade,witness?2:1);assert.equal(s.energy,witness?92:94);assert.equal(s.skills.battle,0);roundtrip(s);}});
test('步骤与选择存档拒绝伪造，旧档兼容；截止前时间不足和跨日到期不发钱物',()=>{const s=begin('lostPouch');for(const phase of [-1,4,'1']){const b=structuredClone(s);b.job.phase=phase;assert.throws(()=>restore(JSON.stringify(b)),/步骤/);}const b=structuredClone(s);b.pending={type:'errand',id:'herbalEscort'};assert.throws(()=>restore(JSON.stringify(b)),/步骤/);const old=fresh();roundtrip(old);travel(s,'road');s.day=3;s.minute=1430;assert.equal(choose(s,'clue'),false);assert.equal(s.job.phase,0);advance(s,20);assert.equal(s.job,null);encounter(s);assert.equal(s.coins,30);assert.equal(s.bag.food,2);roundtrip(s);});

test('疲劳可以暂缓后休息，恢复后继续；跨日步骤保存实际进度，无自动领奖',()=>{const s=begin('lostPouch');travel(s,'road');s.energy=0;assert.equal(choose(s,'clue'),false);assert.ok(act(s,'pauseErrand'));assert.equal(s.pending,null);roundtrip(s);assert.ok(act(s,'resumeErrand'));assert.ok(act(s,'pauseErrand'));assert.ok(act(s,'rest'));assert.equal(s.energy,30);assert.equal(s.pending.type,'errand');s.minute=1430;choose(s,'clue');assert.equal(s.day,2);assert.equal(s.job.phase,1);assert.equal(s.pending,null);assert.equal(s.coins,30);roundtrip(s);});
