import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,acceptJob,act,restore} from '../src/rebuild/engine.js';
import {jobSkillBlocker} from '../src/rebuild/contracts.js';
import {jobs} from '../src/rebuild/content.js';
import {setPlan,runPlan} from '../src/rebuild/planner.js';
test('农活和作坊短工按实际时间精力付工资，仅结算对应生活技能，不送材料或成品',()=>{for(const [id,place,skill,reward] of [['fieldWork','village','farming',12],['smithWork','forge','forge',16]]){const s=fresh();if(skill==='forge')s.skills.forge=100;assert.equal(acceptJob(s,id),true);s.place=place;const bag=structuredClone(s.bag),xp=s.skills[skill];assert.equal(act(s,'deliver'),true);assert.equal(s.minute,660);assert.equal(s.energy,76);assert.equal(s.coins,30+reward);assert.equal(s.skills[skill],xp+2);assert.deepEqual(s.bag,bag);assert.equal(s.skills.fist,0);assert.equal(s.skills.carry,0);assert.equal(s.skills.trade,0);assert.equal(s.job,null);assert.equal(acceptJob(s,id),false);assert.deepEqual(restore(JSON.stringify(s)),s)}});
test('作坊短工共用技能门槛，差一点仍不准接；执行时也检查，不提前发工资',()=>{const s=fresh();s.skills.forge=99;assert.match(jobSkillBlocker(s,jobs.smithWork),/需要锻造 Lv2/);assert.equal(acceptJob(s,'smithWork'),false);assert.equal(s.minute,480);s.skills.forge=100;assert.equal(jobSkillBlocker(s,jobs.smithWork),null);assert.equal(acceptJob(s,'smithWork'),true);s.place='forge';s.skills.forge=0;assert.equal(act(s,'deliver'),false);assert.equal(s.coins,30);assert.equal(s.energy,100);assert.equal(s.job.id,'smithWork')});
test('开工须完整落在工时内，不把三小时塞进半小时，失败保留约定和资源',()=>{for(const [id,place,minute] of [['fieldWork','village',300],['smithWork','forge',360],['fieldWork','village',901],['smithWork','forge',1020]]){const s=fresh();s.skills.forge=100;acceptJob(s,id);s.place=place;s.minute=minute;assert.equal(act(s,'deliver'),false);assert.equal(s.minute,minute);assert.equal(s.coins,30);assert.equal(s.energy,100);assert.equal(s.job.id,id)}const s=fresh();acceptJob(s,'fieldWork');s.place='village';s.minute=900;assert.equal(act(s,'deliver'),true);assert.equal(s.minute,1080)});
test('重伤禁止劳力工作，精力不足计划暂停，疲劳减少成长，原存档仍可恢复',()=>{for(const id of ['fieldWork','unload']){const s=fresh();acceptJob(s,id);s.place=jobs[id].place;s.hp=24;assert.equal(act(s,'deliver'),false);assert.equal(s.coins,30);assert.equal(s.energy,100)}const wounded=fresh();wounded.hp=24;assert.equal(act(wounded,'work'),false);assert.equal(wounded.coins,30);const s=fresh();s.place='village';s.energy=23;acceptJob(s,'fieldWork');setPlan(s,'交货；休息');runPlan(s);assert.equal(s.coins,30);assert.deepEqual(s.plan,['交货','休息']);s.energy=30;runPlan(s);assert.equal(s.skills.farming,1);assert.equal(s.coins,42);assert.equal(s.job,null);assert.deepEqual(restore(JSON.stringify(s)),s)});
