import test from 'node:test';import assert from 'node:assert/strict';import {fresh,act,equip,fight,restore,choose} from '../src/rebuild/engine.js';import {arts,activeArt,artAssessmentBlocker} from '../src/rebuild/martial.js';import {strike} from '../src/rebuild/combat.js';
function pupil(key='steadySword'){const s=fresh(),a=arts[key];s.place='liuxi';s.bag[a.weapon]=1;s.weapon=a.weapon;s.skills[a.basic]=100;return s}
function learned(key='steadySword'){const s=pupil(key);act(s,key==='steadySword'?'learnSwordArt':'learnStaffArt');act(s,key==='steadySword'?'equipSwordArt':'equipStaffArt');return s}
test('两门真实学习扣学费、时间精力，仅增加对应入门与兵器经验，不自动选用',()=>{for(const key of Object.keys(arts)){const s=pupil(key),a=arts[key];assert.equal(act(s,key==='steadySword'?'learnSwordArt':'learnStaffArt'),true);assert.equal(s.coins,10);assert.equal(s.minute,540);assert.equal(s.energy,88);assert.equal(s.arts[key],true);assert.equal(s.art,null);assert.equal(s.skills[key],1);assert.equal(s.skills[a.basic],101);assert.match(s.result.join('；'),new RegExp(a.name+' Lv1：0/100 → 1/100'));assert.equal(act(s,key==='steadySword'?'learnSwordArt':'learnStaffArt'),false);assert.equal(s.coins,10);assert.deepEqual(restore(JSON.stringify(s)),s)}});
test('不足基础、错兵器、钱、精力、伤势和授课时段不会收费或学会，17点可完成',()=>{for(const change of [s=>s.skills.sword=99,s=>s.weapon='unarmed',s=>s.coins=19,s=>s.energy=11,s=>s.hp=24,s=>s.minute=1021,s=>s.place='town']){const s=pupil();change(s);const before=structuredClone(s);assert.equal(act(s,'learnSwordArt'),false);for(const k of ['coins','minute','energy','skills','arts','bag'])assert.deepEqual(s[k],before[k])}const s=pupil();s.minute=1020;assert.equal(act(s,'learnSwordArt'),true);assert.equal(s.minute,1080)});
test('主动选用不加经验，练习按实际动作结算两项技能，错误地点和兵器不成长',()=>{const s=learned();assert.equal(s.skills.steadySword,1);assert.equal(s.minute,545);assert.equal(act(s,'practiceArt'),true);assert.equal(s.skills.steadySword,3);assert.equal(s.skills.sword,102);assert.equal(s.energy,72);assert.equal(s.minute,665);equip(s,'unarmed');assert.equal(activeArt(s),null);assert.equal(act(s,'practiceArt'),false);equip(s,'sword');s.place='town';assert.equal(act(s,'practiceArt'),false);assert.deepEqual(restore(JSON.stringify(s)),s)});
test('新招具有可比较的攻守差异，消耗6精力并精确增长武艺、兵器与实战判断',()=>{for(const key of Object.keys(arts)){const s=learned(key);s.combat={name:'拦路人',hp:32,attack:8,spar:false};const normal=strike(s,'attack',()=>0).damage,art=strike(s,'art',()=>0).damage;assert.equal(art-normal,key==='steadySword'?1:-2);const hp=s.hp,energy=s.energy,basic=s.skills[arts[key].basic];assert.equal(fight(s,'art'),true);assert.equal(s.energy,energy-6);assert.equal(s.hp,hp-(key==='steadySword'?7:4));assert.equal(s.skills[key],2);assert.equal(s.skills[arts[key].basic],basic+1);assert.equal(s.skills.battle,1);assert.deepEqual(restore(JSON.stringify(s)),s)}const s=learned();s.skills.steadySword=100;s.combat={name:'持棍拦路人',hp:40,attack:6,spar:false};assert.equal(strike(s,'art',()=>0).damage-strike(s,'attack',()=>0).damage,2)});
test('未学、未选、兵器不符或缺精力不能打新招，撤离不给新武艺经验',()=>{const s=pupil();s.combat={name:'拦路人',hp:32,attack:8,spar:false};const before=structuredClone(s);assert.equal(fight(s,'art'),false);assert.equal(s.combat.hp,before.combat.hp);assert.equal(s.energy,before.energy);const l=learned();l.combat={name:'拦路人',hp:32,attack:8,spar:false};l.energy=5;assert.equal(fight(l,'art'),false);assert.equal(l.skills.steadySword,1);assert.equal(fight(l,'flee'),true);assert.equal(l.skills.steadySword,1)});
test('练习疲劳减半，满级不溢出；新武艺不会因普通招式或听闲话增长',()=>{const s=learned();s.energy=35;act(s,'practiceArt');assert.equal(s.energy,19);assert.equal(s.skills.steadySword,2);assert.equal(s.skills.sword,102);s.energy=100;s.skills.steadySword=2100;s.skills.sword=2100;act(s,'practiceArt');assert.equal(s.skills.steadySword,2100);assert.equal(s.skills.sword,2100);assert.deepEqual(restore(JSON.stringify(s)),s);const l=learned();l.combat={name:'周师傅',hp:45,attack:5,spar:true};fight(l,'attack');assert.equal(l.skills.steadySword,1);assert.equal(l.skills.battle,0)});
test('進阶考较需新武艺Lv2，获胜只记录日期，撤离或师傅收手不算通过',()=>{for(const key of Object.keys(arts)){const s=learned(key);assert.match(artAssessmentBlocker(s),/Lv2/);s.skills[key]=100;s.energy=100;s.hp=100;const money=s.coins;assert.equal(act(s,'artAssessment'),true);assert.deepEqual(restore(JSON.stringify(s)),s);let turns=0;while(s.combat){assert.ok(turns++<15);fight(s,'art')}assert.equal(s.artPassed[key],1);assert.equal(s.coins,money);assert.equal(s.skills.battle,0);assert.equal(act(s,'artAssessment'),false);assert.deepEqual(restore(JSON.stringify(s)),s)}const flee=learned();flee.skills.steadySword=100;act(flee,'artAssessment');fight(flee,'flee');assert.equal(flee.artPassed.steadySword,undefined);const stop=learned();stop.skills.steadySword=100;stop.hp=70;act(stop,'artAssessment');while(stop.combat)fight(stop,'heavy',()=>1);assert.equal(stop.artPassed.steadySword,undefined);assert.equal(stop.dead,false)});
test('旧存档补未学状态和零经验，拒绝伪造学习、选择或考较，不影响旧基础考较',()=>{const s=fresh();delete s.arts;delete s.art;delete s.artPassed;delete s.skills.steadySword;delete s.skills.shelterStaff;delete s.relations.tutor;s.coins=77;const old=restore(JSON.stringify(s));assert.equal(old.coins,77);assert.deepEqual(old.arts,{steadySword:false,shelterStaff:false});assert.equal(old.skills.steadySword,0);assert.equal(old.art,null);for(const change of [s=>{s.arts.toString=true;s.art='toString'},s=>s.art='steadySword',s=>s.skills.steadySword=1,s=>s.artPassed={steadySword:1}]){const forged=fresh();change(forged);assert.throws(()=>restore(JSON.stringify(forged)),/武艺/)}const mixed=learned();mixed.skills.steadySword=100;mixed.combat={name:'周师傅',hp:45,attack:7,spar:true,artAssessment:'steadySword'};assert.throws(()=>restore(JSON.stringify(mixed)),/进阶/)});
