import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,act,trade,restore} from '../src/rebuild/engine.js';
import {setPlan,runPlan} from '../src/rebuild/planner.js';
test('猎具可购买或制作，制作只增长木工，不提前给狩猎经验',()=>{const s=fresh();trade(s,'buy','trap');assert.equal(s.coins,18);assert.equal(s.bag.trap,1);assert.equal(s.skills.hunt,0);const maker=fresh();maker.place='forge';maker.bag.wood=2;maker.bag.iron=1;act(maker,'craftTrap',()=>1);assert.equal(maker.bag.wood,0);assert.equal(maker.bag.iron,0);assert.equal(maker.bag.trap,1);assert.equal(maker.skills.woodwork,2);assert.equal(maker.skills.hunt,0);assert.equal(maker.energy,86);assert.equal(maker.minute,600)});
test('捕猎须猎具、地点和体力，成功与失败均真实耗三小时，只成长狩猎',()=>{const s=fresh();assert.equal(act(s,'hunt'),false);s.place='hill';assert.equal(act(s,'hunt'),false);assert.equal(s.minute,480);s.bag.trap=1;act(s,'hunt',()=>0);assert.equal(s.bag.meat,1);assert.equal(s.bag.trap,1);assert.equal(s.minute,660);assert.equal(s.energy,80);assert.equal(s.skills.hunt,2);act(s,'hunt',()=>1);assert.equal(s.bag.meat,1);assert.equal(s.bag.trap,1);assert.equal(s.minute,840);assert.equal(s.energy,60);assert.equal(s.skills.hunt,4);assert.ok(Object.entries(s.skills).filter(([key])=>key!=='hunt').every(([,xp])=>xp===0));s.energy=19;assert.equal(act(s,'hunt'),false);assert.equal(s.energy,19);s.energy=100;s.hp=24;assert.equal(act(s,'hunt'),false);assert.equal(s.minute,840)});
test('疲惫降低捕猎机会和练习，失败不送材料，满额不继续增加',()=>{const s=fresh();s.place='hill';s.bag.trap=1;s.energy=20;act(s,'hunt',()=>0.5);assert.equal(s.bag.meat,0);assert.equal(s.skills.hunt,1);assert.equal(s.energy,0);s.energy=100;s.skills.hunt=2100;act(s,'hunt',()=>0);assert.equal(s.bag.meat,1);assert.equal(s.skills.hunt,2100);assert.ok(!s.result.some(x=>x.startsWith('狩猎 Lv')))});
test('猎获可真实出售或制成干粮，烹饪与吃饭不重复增加狩猎经验',()=>{const s=fresh();s.place='hill';s.bag.trap=1;act(s,'hunt',()=>0);act(s,'hunt',()=>0);s.place='town';trade(s,'sell','meat');assert.equal(s.coins,36);assert.equal(s.bag.meat,1);assert.equal(s.skills.trade,1);s.place='forge';s.bag.wood=1;act(s,'cookMeat',()=>1);assert.equal(s.bag.meat,0);assert.equal(s.bag.wood,0);assert.equal(s.bag.food,4);assert.equal(s.skills.cook,2);assert.equal(s.skills.hunt,4);assert.match(s.result.join(' '),/材料消耗：猎物肉 -1、木料 -1/);const energy=s.energy;act(s,'eat');assert.equal(s.bag.food,3);assert.equal(s.energy,energy+12);assert.equal(s.skills.cook,2);assert.deepEqual(restore(JSON.stringify(s)),s)});
test('新烹饪配方缺料不扣，疲劳失败仍精确记录库存',()=>{const s=fresh();s.place='forge';s.bag.meat=1;assert.equal(act(s,'cookMeat'),false);assert.equal(s.bag.meat,1);assert.equal(s.minute,480);s.bag.wood=1;s.energy=8;act(s,'cookMeat',()=>0);assert.equal(s.bag.meat,0);assert.equal(s.bag.wood,0);assert.equal(s.bag.food,2);assert.equal(s.skills.cook,1);assert.match(s.result.join(' '),/疲劳导致失误/)});
test('原存档补零保留历史，自由计划支持制作猎具；坏库存拒绝',()=>{const s=fresh();delete s.bag.trap;delete s.bag.meat;delete s.skills.hunt;s.bag.wood=4;s.skills.woodwork=8;const old=restore(JSON.stringify(s));assert.equal(old.bag.trap,0);assert.equal(old.bag.meat,0);assert.equal(old.skills.hunt,0);assert.equal(old.bag.wood,4);assert.equal(old.skills.woodwork,8);old.place='forge';old.bag.iron=1;setPlan(old,'制作猎具；休息');runPlan(old);assert.equal(old.bag.trap,1);assert.equal(old.skills.woodwork,10);assert.equal(old.skills.hunt,0);for(const bad of [{bag:{...fresh().bag,meat:-1}},{skills:{...fresh().skills,hunt:2101}}])assert.throws(()=>restore(JSON.stringify({...fresh(),...bad})))});
