import {command} from '../src/rebuild/commands.js';
import {test} from 'node:test';import assert from 'node:assert/strict';
import {fresh,restore,equip,trade,act,fight} from '../src/rebuild/engine.js';
test('购买不自动装备，主动换用不扣库存或精力，卸下仍保留兵器',()=>{const s=fresh();trade(s,'buy','sword');assert.equal(s.coins,6);assert.equal(s.weapon,'unarmed');const energy=s.energy;equip(s,'sword');assert.equal(s.bag.sword,1);assert.equal(s.weapon,'sword');assert.equal(s.energy,energy);assert.equal(s.minute,500);equip(s,'unarmed');assert.equal(s.weapon,'unarmed');assert.equal(s.bag.sword,1);assert.deepEqual(restore(JSON.stringify(s)),s)});
test('剑术和棍法只由相应兵器成长，不给无关拳脚经验',()=>{for(const key of ['staff','sword']){const s=fresh();s.bag[key]=1;s.place='road';equip(s,key);act(s,'train');assert.equal(s.skills[key],2);assert.equal(s.skills.fist,0);s.learned=true;s.combat={name:'周师傅',hp:45,attack:5,spar:true};fight(s,'inner');assert.equal(s.skills[key],3);assert.equal(s.skills.inner,1);assert.equal(s.skills.fist,0);assert.equal(s.combat.hp,key==='staff'?34:33)}});
test('不持有或交手中不能换兵器，物品放在背包不加伤害',()=>{const s=fresh();equip(s,'sword');assert.equal(s.weapon,'unarmed');assert.equal(s.minute,480);s.bag.staff=1;s.combat={name:'周师傅',hp:45,attack:5,spar:true};equip(s,'staff');assert.equal(s.weapon,'unarmed');fight(s,'attack');assert.equal(s.combat.hp,37);assert.equal(s.skills.fist,1);assert.equal(s.skills.staff,0)});
test('旧存档迁移保留物品与已有经验，不猜造剑术经验；非法装备拒绝',()=>{const s=fresh();delete s.weapon;delete s.bag.sword;delete s.skills.staff;delete s.skills.sword;s.bag.staff=1;s.skills.fist=25;const old=restore(JSON.stringify(s));assert.equal(old.weapon,'staff');assert.equal(old.skills.fist,25);assert.equal(old.skills.staff,0);assert.equal(old.skills.sword,0);assert.throws(()=>restore(JSON.stringify({...fresh(),weapon:'sword'})));assert.throws(()=>restore(JSON.stringify({...fresh(),weapon:'toString'})))});

test('自由输入兵器练习不会偷偷结算其他武学',()=>{const s=fresh();s.place='road';command(s,'练剑');assert.equal(s.skills.fist,0);assert.equal(s.minute,480);s.bag.sword=1;command(s,'装备铁剑');command(s,'练剑');assert.equal(s.skills.sword,2);assert.equal(s.skills.fist,0);command(s,'练拳');assert.equal(s.skills.fist,0);command(s,'卸下兵器');assert.equal(s.weapon,'unarmed')});
