import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,choose} from '../src/rebuild/engine.js';
import {choiceDetails} from '../src/rebuild/encounter-view.js';
import {events} from '../src/rebuild/content.js';import {discoveries} from '../src/rebuild/discoveries.js';
import {maxXP} from '../src/rebuild/progression.js';
test('选择预览只读，精确展示消耗库存、工钱和相关技能',()=>{const s=fresh();s.bag.wood=2;const before=structuredClone(s);const lines=choiceDetails(s,events.boatRepair.choices[0]).join('；');assert.match(lines,/木料2（现有2）/);assert.match(lines,/铜钱：\+16文/);assert.match(lines,/相关技能：木工/);assert.doesNotMatch(lines,/暂不能|锻造/);assert.deepEqual(s,before)});
test('缺料、伤势和精力提示与实际修船限制一致，离开不受限制',()=>{const s=fresh();s.place='dock';s.bag.wood=1;s.hp=24;s.energy=11;s.events=[{id:'repair',kind:'boatRepair',status:'open',expires:3}];s.pending={type:'world',id:'repair'};const lines=choiceDetails(s,events.boatRepair.choices[0]).join('；');for(const label of ['木料不足','受伤太重','精力不足'])assert.ok(lines.includes(label));assert.equal(choose(s,'help'),false);assert.deepEqual(choiceDetails(s,events.boatRepair.choices.find(c=>c.id==='leave')),[]);assert.equal(choose(s,'leave'),true)});
test('探索选择展示真实物资和结束地点，不虚构善举报酬',()=>{const s=fresh();s.place='road';const medicine=choiceDetails(s,discoveries.traveler.choices[0]).join('；');assert.match(medicine,/草药1（现有0）/);assert.doesNotMatch(medicine,/铜钱|相关技能/);assert.match(choiceDetails(s,discoveries.traveler.choices[1]).join('；'),/结束地点：河湾村/);assert.match(choiceDetails(s,discoveries.herbs.choices[0]).join('；'),/获得：草药2/);assert.match(choiceDetails(s,discoveries.purse.choices[1]).join('；'),/铜钱：\+3文/)});
test('技能满级预览不承诺额外成长，普通晚饭不关联无关技能',()=>{const s=fresh();s.skills.woodwork=maxXP;assert.match(choiceDetails(s,events.boatRepair.choices[0]).join('；'),/木工【已满，不增长】/);assert.doesNotMatch(choiceDetails(s,events.villageMeal.choices[0]).join('；'),/相关技能|铜钱/)});
