import {command} from '../src/rebuild/commands.js';
import test from 'node:test';import assert from 'node:assert/strict';import {fresh,cargoTrade,travel,choose,restore,act} from '../src/rebuild/engine.js';import {advance} from '../src/rebuild/world.js';import {tradeQuote,tradeStatus} from '../src/rebuild/risk-trade.js';
const buy=(roll,n=6)=>{const s=fresh();s.coins=100;assert.ok(cargoTrade(s,'buy',n,()=>roll));return s;};const go=s=>{travel(s,'road');travel(s,'bamboo');assert.equal(s.pending.type,'trade');};const save=s=>assert.deepEqual(restore(JSON.stringify(s)),s);
test('本金实扣、茶货入库存，无进货经验；读档保留本批行情且不能重复进货',()=>{const s=buy(.1,3);assert.equal(s.coins,70);assert.equal(s.bag.tea,3);assert.equal(s.energy,99);assert.equal(s.skills.trade,0);assert.equal(s.tradeRun.heard,false);save(s);const loaded=restore(JSON.stringify(s));assert.equal(loaded.tradeRun.kind,'surge');assert.equal(cargoTrade(loaded,'buy',1,()=>.99),false);assert.equal(loaded.coins,70);assert.equal(loaded.tradeRun.kind,'surge');assert.equal(loaded.bag.tea,3);});
test('缺货行情大赚，途中暂停不替玩家卖货，实际步行零精力，成交后盈亏留档',()=>{const s=buy(.1);go(s);assert.equal(s.energy,99);assert.equal(s.coins,40);assert.match(s.result.join(' '),/可靠行情.*22文/);save(s);assert.equal(cargoTrade(s,'sell',6),false);choose(s,'continue');travel(s,'liuxi');assert.equal(tradeQuote(s).price,22);cargoTrade(s,'sell',6);assert.equal(s.coins,172);assert.equal(s.bag.tea,0);assert.match(tradeStatus(s),/本金60文，收回132文，盈利72文/);assert.equal(s.skills.trade,1);assert.match(s.result.join(' '),/经商 Lv1：0\/100 → 1\/100（\+1）/);assert.equal(cargoTrade(s,'sell',1),false);assert.equal(cargoTrade(s,'buy',1),false);save(s);});
test('货多会真实亏本；已知报价成交时不暗抽另一个结果',()=>{const s=buy(.9);go(s);choose(s,'continue');travel(s,'liuxi');assert.equal(tradeQuote(s).price,5);cargoTrade(s,'sell',6,()=>.01);assert.equal(s.coins,70);assert.equal(s.tradeRun.kind,'glut');assert.match(tradeStatus(s),/亏损30文/);assert.equal(s.bag.tea,0);save(s);});
test('回镇止损和转卖有成本及有限额度，不保证全批盈利，不凭空补钱物',()=>{const s=buy(.9);go(s);choose(s,'village');travel(s,'hill');travel(s,'village');assert.equal(tradeQuote(s).price,12);assert.equal(cargoTrade(s,'sell',6),false);assert.equal(s.bag.tea,6);cargoTrade(s,'sell',1);assert.equal(s.coins,52);assert.equal(tradeQuote(s).capacity,0);assert.equal(cargoTrade(s,'sell',1),false);travel(s,'town');cargoTrade(s,'sell',5);assert.equal(s.coins,82);assert.match(tradeStatus(s),/亏损18文/);assert.equal(s.tradeRun.soldAlt,1);save(s);});
test('平稳行情限收三包，余货不自动卖；分批成交总账准确，不超额成交',()=>{const s=buy(.4);go(s);choose(s,'continue');travel(s,'liuxi');assert.equal(tradeQuote(s).capacity,3);assert.equal(cargoTrade(s,'sell',6),false);assert.equal(s.coins,40);cargoTrade(s,'sell',1);assert.equal(tradeQuote(s).capacity,2);cargoTrade(s,'sell',2);assert.equal(s.bag.tea,3);assert.equal(s.tradeRun.revenue,42);assert.equal(tradeQuote(s).capacity,0);save(s);assert.equal(cargoTrade(s,'sell',1),false);});
test('跨日行情跌价并提示，存货与收购额度不刷新；报价有底线，无自动收益',()=>{const s=buy(.1);go(s);choose(s,'wait');s.place='liuxi';cargoTrade(s,'sell',1);const coins=s.coins;advance(s,1440);assert.equal(tradeQuote(s).price,20);assert.equal(tradeQuote(s).capacity,5);assert.equal(s.bag.tea,5);assert.equal(s.coins,coins);assert.ok(s.news.some(x=>x.includes('茶货未售出')));advance(s,20*1440);assert.equal(tradeQuote(s).price,2);assert.equal(s.bag.tea,5);save(s);});
test('本金、地点、数量、营业时间和精力不足整笔拒绝；疲劳按实际经商成长结算',()=>{const s=fresh();for(const n of [0,2,4,1.5,6])assert.equal(cargoTrade(s,'buy',n),false);assert.equal(s.coins,30);s.minute=1186;assert.equal(cargoTrade(s,'buy',1),false);s.minute=480;s.energy=0;assert.equal(cargoTrade(s,'buy',1),false);s.energy=10;assert.ok(cargoTrade(s,'buy',1,()=>.1));assert.ok(cargoTrade(s,'sell',1));assert.equal(s.skills.trade,1);assert.equal(s.coins,26);save(s);});
test('旧档迁移不编造库存；拒绝伪造批次、货量与途中选择，死者不能交易',()=>{const old=fresh();delete old.tradeRun;delete old.tradeDay;delete old.bag.tea;const loaded=restore(JSON.stringify(old));assert.equal(loaded.bag.tea,0);assert.equal(loaded.tradeRun,null);const s=buy(.1);for(const edit of [b=>b.tradeRun.kind='toString',b=>b.tradeRun.remaining=7,b=>b.bag.tea=5,b=>b.tradeRun.revenue=999,b=>b.tradeDay=0,b=>b.pending={type:'trade'}]){const b=structuredClone(s);edit(b);assert.throws(()=>restore(JSON.stringify(b)),/贸易/);}s.dead=true;s.hp=0;assert.equal(cargoTrade(s,'sell',1),false);});

test('途中选择真正改变待执行路线，暂缓保留旧安排，不自动移动或卖出',()=>{for(const [choice,end] of [['continue','去柳溪集'],['return','去青石镇'],['village','去河湾村']]){const s=buy(.9);go(s);s.plan=['去旧渡口'];const before=s.coins;choose(s,choice);assert.equal(s.plan.at(-1),end);assert.equal(s.place,'bamboo');assert.equal(s.coins,before);assert.equal(s.bag.tea,6);save(s);}const s=buy(.1);go(s);s.plan=['去柳溪集'];choose(s,'wait');assert.deepEqual(s.plan,['去柳溪集']);});

test('自由输入真实进货和止损，与普通商铺隔离，封顶技能不再增长',()=>{const s=fresh();assert.ok(command(s,'进茶货1包'));assert.equal(s.bag.tea,1);assert.equal(s.coins,20);assert.equal(command(s,'卖本批茶货'),false);s.skills.trade=2100;assert.ok(command(s,'卖茶货1包'));assert.equal(s.coins,26);assert.equal(s.bag.tea,0);assert.equal(s.skills.trade,2100);save(s);});
