import test from 'node:test';
import assert from 'node:assert/strict';
import {fresh,choose,act,restore,trade,fight} from '../src/rebuild/engine.js';
import {advance,encounter,npcPlace,npcScheduleText} from '../src/rebuild/world.js';
import {validEchoes} from '../src/rebuild/continuity.js';
const save=s=>restore(JSON.stringify(s));
function event(kind,place){const s=fresh();s.place=place;s.events=[{id:kind+'-1',kind,status:'open',expires:3}];s.pending={type:'world',id:kind+'-1'};return s;}
test('帮助两日后产生一次回礼，需要亲自选择；领取不赠经验，存档不重发',()=>{const s=event('herbs','village');assert.ok(choose(s,'help'));assert.equal(s.bag.herb,0);assert.deepEqual(s.echoes.herbs,{day:1,done:false});assert.deepEqual(save(s).echoes,s.echoes);advance(s,2880);assert.equal(s.day,3);assert.equal(s.bag.herb,0);encounter(s);while(s.pending?.id!=='herbThanks-3'){assert.ok(s.pending);choose(s,'leave');encounter(s);}assert.equal(s.pending.id,'herbThanks-3');assert.ok(choose(s,'take'));assert.equal(s.bag.herb,1);assert.equal(s.skills.herb,0);assert.match(s.result.join(' '),/草药：0 → 1/);assert.match(s.result.join(' '),/精力：96 → 96/);s.events.forEach(e=>e.status='resolved');s.events.push({id:'herbs-3',kind:'herbs',status:'open',expires:5});s.pending={type:'world',id:'herbs-3'};choose(s,'help');advance(s,2880);assert.equal(s.events.filter(e=>e.kind==='herbThanks').length,1);assert.ok(save(s));});
test('忽略事件仍有结局，不送回礼；回礼错过后真实失效',()=>{const ignored=event('boatRepair','dock');choose(ignored,'leave');advance(ignored,2880);assert.deepEqual(ignored.echoes,{});assert.ok(ignored.news.some(x=>x.includes('补好舱板')));const helped=event('boatRepair','dock');helped.bag.wood=2;choose(helped,'help');advance(helped,2880);assert.equal(helped.bag.food,2);advance(helped,2880);assert.equal(helped.events.find(e=>e.kind==='boatThanks').status,'resolved');assert.equal(helped.bag.food,2);assert.ok(helped.news.some(x=>x.includes('无人领取')));});
test('NPC固定小事改变真实去向，离开后回原住处；只读作息不改时间',()=>{const s=fresh();s.day=3;assert.equal(npcPlace(s,'merchant'),'ferry');assert.match(npcScheduleText('merchant',s),/进货/);s.minute=1000;assert.equal(npcPlace(s,'merchant'),'inn');s.day=5;s.minute=480;assert.equal(npcPlace(s,'boatman'),'dock');s.minute=1200;assert.equal(npcPlace(s,'boatman'),'liuxi');s.day=6;s.minute=480;assert.equal(npcPlace(s,'master'),'liuxi');assert.ok(save(s));});
test('赶集有预告，8点开场，真实扣钱加物，不重复成交，每七日再开',()=>{const s=fresh();advance(s,960);assert.equal(s.day,2);assert.equal(s.minute,0);encounter(s);assert.equal(s.pending,null);advance(s,480);encounter(s);assert.equal(s.pending.id,'weeklyMarket-2');const before=s.coins;choose(s,'seed');assert.equal(s.coins,before-4);assert.equal(s.bag.seed,2);assert.equal(s.energy,99);assert.equal(s.skills.trade,0);assert.equal(choose(s,'seed'),false);advance(s,7*1440);assert.ok(s.events.some(e=>e.kind==='weeklyMarket'&&e.id==='weeklyMarket-9'));assert.ok(save(s));});
test('赶集没钱整笔不成交；活动跨日不可领，码头工作必须18点前做完',()=>{const s=fresh();s.day=2;s.events=[{id:'weeklyMarket-2',kind:'weeklyMarket',expires:4,status:'open'}];s.pending={type:'world',id:'weeklyMarket-2'};s.coins=0;assert.equal(choose(s,'food'),false);assert.equal(s.bag.food,2);assert.equal(s.minute,480);choose(s,'leave');assert.equal(s.pending,null);const d=fresh();d.day=6;d.place='dock';d.minute=961;d.events=[{id:'weeklyDock-6',kind:'weeklyDock',expires:8,status:'open'}];d.pending={type:'world',id:'weeklyDock-6'};assert.equal(choose(d,'work'),false);assert.equal(d.coins,30);d.minute=960;assert.ok(choose(d,'work'));assert.equal(d.minute,1080);assert.equal(d.coins,44);assert.equal(d.energy,84);assert.equal(d.skills.carry,1);advance(d,1440);assert.ok(save(d));});
test('公开切磋主动进入并可撤离，无奖金或考较；回礼记录拒绝伪造并兼容旧存档',()=>{const s=fresh();s.day=4;s.place='liuxi';s.events=[{id:'weeklySpar-4',kind:'weeklySpar',expires:6,status:'open'}];encounter(s);assert.equal(s.combat,null);choose(s,'spar');assert.equal(s.combat.name,'周师傅');assert.ok(save(s));fight(s,'attack');assert.equal(s.skills.fist,1);assert.equal(s.skills.battle,0);fight(s,'flee');assert.equal(s.combat,null);assert.equal(s.coins,30);assert.deepEqual(s.assessments,{});const old=fresh();delete old.echoes;assert.deepEqual(save(old).echoes,{});for(const echoes of [{toString:{day:1,done:false}},{herbs:{day:2,done:false}},{herbs:{day:1,done:true}},[]]){const bad=fresh();bad.echoes=echoes;assert.equal(!!validEchoes(bad),false);assert.throws(()=>save(bad));}});
