import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,restore} from '../src/rebuild/engine.js';
import {setPlan,runPlan,skipStep,clearPlan,splitPlan} from '../src/rebuild/planner.js';
test('多项计划先预览，不推进时间或奖励；不认识的行动和超量输入整体拒绝',()=>{const s=fresh();assert.equal(setPlan(s,'去码头；打零工；休息'),true);assert.equal(s.minute,480);assert.equal(s.coins,30);assert.equal(s.energy,100);assert.deepEqual(s.plan,['去码头','打零工','休息']);assert.equal(setPlan(s,'采药；休息'),false);clearPlan(s);assert.equal(setPlan(s,'去码头；凭空获得秘籍'),false);assert.deepEqual(s.plan,[]);assert.equal(setPlan(s,Array(9).fill('休息').join(';')),false);assert.deepEqual(splitPlan(' 去码头、钓鱼，休息\n打零工 '),['去码头','钓鱼','休息','打零工'])});
test('按顺序执行并逐项保存与结算，移动零精力，所有相关成长可见',()=>{const s=fresh();setPlan(s,'去码头；打零工；休息');const saves=[];assert.equal(runPlan(s,x=>saves.push(restore(JSON.stringify(x)))),true);assert.equal(s.place,'dock');assert.equal(s.minute,810);assert.equal(s.coins,42);assert.equal(s.energy,100);assert.equal(s.skills.carry,2);assert.deepEqual(s.plan,[]);assert.equal(saves.length,3);assert.deepEqual(saves.map(x=>x.plan.length),[2,1,0]);assert.match(s.result.join('\n'),/精力：100 → 76（-24）/);assert.match(s.result.join('\n'),/精力：76 → 100（\+24）/);assert.match(s.result.join('\n'),/搬运 Lv1：0\/100 → 2\/100（\+2）/)});
test('缺精力、营业时间、材料或路线时停留在失败项，不擅自恢复和瞬移',()=>{for(const [plan,setup] of [['打零工；休息',s=>s.energy=0],['买铁料；休息',s=>s.minute=1260],['打造工具；休息',s=>s.place='forge'],['去竹林；休息',()=>{}]]){const s=fresh();setup(s);setPlan(s,plan);const before=structuredClone(s);assert.equal(runPlan(s),false);assert.equal(s.energy,before.energy);assert.equal(s.minute,before.minute);assert.equal(s.coins,before.coins);assert.equal(s.place,before.place);assert.deepEqual(s.plan,before.plan);assert.match(s.result.join(' '),/无法执行/);skipStep(s);assert.deepEqual(s.plan,['休息']);assert.equal(runPlan(s),true)}});
test('发现重要事件暂停，不代替选择，计划在存档中保留',()=>{const s=fresh();s.place='road';s.seed=1;setPlan(s,'探索；休息');assert.equal(runPlan(s),true);assert.equal(s.pending.type,'bandit');assert.equal(s.combat,null);assert.deepEqual(s.plan,['休息']);assert.equal(s.minute,540);assert.equal(s.energy,92);const loaded=restore(JSON.stringify(s));assert.deepEqual(loaded.plan,['休息']);assert.equal(runPlan(loaded),false);assert.equal(loaded.pending.type,'bandit');assert.equal(loaded.energy,92);assert.equal(loaded.minute,540)});
test('切磋与跨日暂停，剩余安排不能被塞进同一天',()=>{const spar=fresh();spar.place='road';setPlan(spar,'切磋；休息');runPlan(spar);assert.ok(spar.combat);assert.deepEqual(spar.plan,['休息']);const s=fresh();s.minute=1380;setPlan(s,'休息；休息');runPlan(s);assert.equal(s.day,2);assert.equal(s.minute,60);assert.deepEqual(s.plan,['休息']);assert.ok(s.news.length);assert.match(s.result.join(' '),/第二天/);runPlan(s);assert.deepEqual(s.plan,[]);assert.equal(s.minute,180)});
test('死亡不执行计划，跳过与清空不消耗资源，旧存档迁移与恶意计划校验',()=>{const s=fresh();delete s.plan;assert.deepEqual(restore(JSON.stringify(s)).plan,[]);s.plan=['休息'];s.hp=0;s.dead=true;assert.equal(runPlan(s),false);assert.equal(s.minute,480);assert.equal(setPlan(s,'去码头'),false);skipStep(s);assert.equal(s.minute,480);assert.equal(s.energy,100);for(const plan of [null,'休息',Array(9).fill('休息'),[''],[9],['字'.repeat(41)]])assert.throws(()=>restore(JSON.stringify({...fresh(),plan})));assert.deepEqual(restore(JSON.stringify(fresh())).plan,[])});
