import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,choose,restore,travel} from '../src/rebuild/engine.js';
import {events} from '../src/rebuild/content.js';
import {advance} from '../src/rebuild/world.js';
const facing=kind=>{const s=fresh();s.place=events[kind].place;s.events=[{id:kind+'-1',kind,status:'open',expires:3}];s.pending={type:'world',id:kind+'-1'};return s};
test('修船实耗材料与精力、发工钱且只结算木工，不向背包生成船',()=>{const s=facing('boatRepair');s.bag.wood=2;assert.equal(choose(s,'help'),true);assert.equal(s.bag.wood,0);assert.equal(s.coins,46);assert.equal(s.minute,540);assert.equal(s.energy,88);assert.equal(s.skills.woodwork,1);assert.ok(Object.entries(s.skills).filter(([k])=>k!=='woodwork').every(([,v])=>v===0));assert.match(s.result.join(' '),/材料消耗：木料 -2/);assert.match(s.result.join(' '),/当前库存：木料 0/);assert.equal(s.events[0].status,'resolved');assert.equal(s.pending,null);assert.deepEqual(restore(JSON.stringify(s)),s);assert.equal(choose(s,'help'),false);assert.equal(s.coins,46)});
test('缺料、重伤或精力不足保持事件待选，不扣钱物时间，仍可离开',()=>{for(const change of [s=>s.bag.wood=1,s=>s.hp=24,s=>s.energy=11]){const s=facing('boatRepair');s.bag.wood=2;change(s);const before=structuredClone(s);assert.equal(choose(s,'help'),false);for(const key of ['bag','coins','minute','energy','pending','events','skills'])assert.deepEqual(s[key],before[key]);assert.equal(choose(s,'leave'),true);assert.equal(s.pending,null);assert.equal(s.events[0].status,'ignored')}});
test('普通买卖只增长相关经商，分享干粮没有无关成长或强制关系',()=>{const trade=facing('marketPrice');choose(trade,'compare');assert.equal(trade.skills.trade,1);assert.equal(trade.coins,30);assert.equal(trade.minute,540);assert.equal(trade.energy,96);const meal=facing('villageMeal');const relations=structuredClone(meal.relations);choose(meal,'share');assert.equal(meal.bag.food,1);assert.equal(meal.minute,510);assert.equal(meal.energy,98);assert.equal(meal.coins,30);assert.deepEqual(meal.relations,relations);assert.ok(Object.values(meal.skills).every(x=>x===0));const empty=facing('villageMeal');empty.bag.food=0;assert.equal(choose(empty,'share'),false);assert.equal(empty.minute,480)});
test('不参与的事件独立结束并给新闻，路过暂停而非自动修船，日常模拟可自然出现新事件',()=>{for(const kind of ['boatRepair','marketPrice','villageMeal']){const s=facing(kind);choose(s,'leave');const bag=structuredClone(s.bag);advance(s,2*1440);assert.equal(s.events[0].status,'resolved');assert.ok(s.news.some(n=>n.includes(events[kind].after)));assert.deepEqual(s.bag,bag);assert.equal(s.coins,30)}const road=fresh();road.events=[{id:'boatRepair-1',kind:'boatRepair',status:'open',expires:3}];travel(road,'dock');assert.equal(road.pending.type,'world');assert.equal(road.coins,30);assert.equal(road.energy,100);const world=fresh(),seen=new Set();for(let i=0;i<120;i++){advance(world,1440);for(const e of world.events)seen.add(e.kind)}assert.ok(['boatRepair','marketPrice','villageMeal'].every(k=>seen.has(k)));assert.deepEqual(restore(JSON.stringify(world)),world)});
