import {command} from './commands.js?v=0.1.0';
import {VERSION,places,resources,items,skills,recipes,markets,people,talents} from './content.js?v=0.1.0';
import {KEY,fresh,move,act,choose,fight,trade,talk,cost,chance,resourceBlocker} from './engine.js?v=0.1.0';
import {date,progress,MAX} from './progression.js?v=0.1.0';
import {npcPlace} from './world.js?v=0.1.0';
import {save,load,importSave} from './storage.js?v=0.1.0';
const $=id=>document.getElementById(id);let state=null,view='world';
const el=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;};
function button(label,fn,disabled=false,preview=''){const b=el('button',label);b.type='button';b.disabled=disabled;b.onclick=()=>{try{fn();persist();render();feedback();if(state.pending||state.combat||state.dead){tab('world');$('scene').scrollIntoView({block:'start'});}}catch(e){$('save-status').textContent='行动未完成：'+e.message;}};if(preview)b.append(el('small',preview));return b;}
function persist(){try{save(state);$('save-status').textContent='已自动保存到此浏览器。';}catch(e){$('save-status').textContent='保存失败，请导出备份：'+e.message;}}
function tab(key){view=key;for(const s of document.querySelectorAll('.view'))s.hidden=s.id!==key;for(const b of $('tabs').children)b.setAttribute('aria-current',b.dataset.tab===key?'page':'false');$('feedback').hidden=true;}
function feedback(){if(!state)return;$('feedback-title').textContent=state.result[0];$('feedback-lines').replaceChildren(...state.result.slice(1).map(t=>el('p',t)));$('feedback').hidden=false;}
const action=(id,label,preview)=>button(label,()=>act(state,id),state.dead||!!state.pending||!!state.combat,preview);
function render(){const s=state;if(!s)return;$('setup').hidden=true;$('game').hidden=false;const p=places[s.place],blocked=s.dead||s.pending||s.combat;$('status').textContent=`${s.name} · 气血 ${s.hp}/100 · 精力 ${s.energy}/100 · ${s.coins}文`;$('place').textContent=p.name;$('clock').textContent=date(s)+' · '+s.weather;$('place-text').textContent=p.text;$('facilities').textContent='设施与资源：'+p.facilities.join('、');
 $('command-input').disabled=!!blocked;$('command-form').querySelector('button').disabled=!!blocked;$('scene').replaceChildren();$('scene').hidden=!blocked;
 if(s.dead){$('scene').append(el('h3','这段人生结束'),el('p','不会自动读档。可在系统页导出经历，再开始新的人生。'));}
 else if(s.combat){$('scene').append(el('h3','与拦路人交手'),el('p','对手气血'+s.combat.hp+'；每次还击6点，防守减到1点；重击70%命中，疲劳伤害降低。撤离必定成功，精力最多2。'));for(const [id,label] of [['attack','出拳 · 精力4'],['heavy','重击 · 精力8'],['guard','防守 · 精力4'],['flee','撤离 · 精力最多2']])$('scene').append(button(label,()=>fight(s,id)));}
 else if(s.pending?.type==='bandit'){$('scene').append(el('h3','旧道上的拦路人'),el('p','实战可能受伤或死亡。可以绕开，没人要求你拼命。'),button('绕开 · 半小时 / 精力0',()=>choose(s,'avoid')),button('交手 · 对手气血28',()=>choose(s,'fight')));}
 else if(s.pending){const d=resources[s.pending.key];$('scene').append(el('h3',d.name),el('p',`${d.minutes}分钟 / 精力${cost(s,d.energy)}，${d.risk*100}%擦伤${d.damage}点气血；也可能没有收获。`),button('确认采集',()=>choose(s,'gather'),!!resourceBlocker(s,s.pending.key)),button('不参与，返回',()=>choose(s,'leave')));}
 $('actions').replaceChildren();if(!blocked){if(p.work)$('actions').append(action('work','做短工',`${s.place==='fields'||s.place==='dock'?'06':'07'}:00–18:00内完成；3小时 / 精力${cost(s,24)}，工钱12文`));if(['inn','village'].includes(s.place))$('actions').append(action('sleep','睡一觉',`8小时，精力恢复至100；${s.place==='inn'?'5文':'免费借宿'}`));if(s.place==='school')$('actions').append(action('train','练入门拳脚','2小时 / 精力18，拳脚经验+2'));if(s.place==='village'&&s.minute>=480&&s.minute+60<=1080)$('actions').append(action('doctor','医者治疗','1小时 / 诊金8文，气血最多恢复50'));$('actions').append(action('rest','歇息','2小时 / 精力0，恢复精力30、气血10'),action('wait','等半小时','只流逝时间，不恢复精力'));const bagShortcut=el('button','查看背包与当地交易');bagShortcut.onclick=()=>tab('bag');$('actions').append(bagShortcut);}
 $('nearby').replaceChildren(...p.routes.map(to=>button('去'+places[to].name,()=>move(s,to),!!blocked,`${places[to].minutes+(s.weather==='雨'&&(places[to].area!=='县城与近郊'||to==='road')?15:0)}分钟 / 精力0`)));
 $('map').replaceChildren();for(const area of ['县城与近郊','河谷与水路','山林与旧道']){const section=el('section','');section.append(el('h3',area));for(const [key,q] of Object.entries(places).filter(([,q])=>q.area===area))section.append(el('p',(key===s.place?'● 你在这里 · ':'')+q.name+' → '+q.routes.map(k=>places[k].name).join('、'),'muted'));$('map').append(section);}
 $('resources').replaceChildren();for(const [key,d] of Object.entries(resources).filter(([,d])=>d.places.includes(s.place))){const n=s.nodes[s.place+':'+key],why=resourceBlocker(s,key),a=el('article','');a.append(el('h3',d.name),el('p',`剩余尝试${n.left}/${d.capacity}；第${n.refreshDay}日恢复。${d.minutes}分钟 / 精力${cost(s,d.energy)}；当前成功率${Math.round(chance(s,d)*100)}%。`,'muted'),el('p','成功获得：'+Object.entries(d.output).map(([k,n])=>items[k]+'×'+n).join('、')+(d.tool?'；需要'+items[d.tool]+'（不消耗）':'')+(d.risk?`；${d.risk*100}%擦伤${d.damage}点气血`:''),'muted'));if(why)a.append(el('p',why,'muted'));a.append(button(d.risk?'查看风险并决定':d.name,()=>act(s,key),!!blocked||!!why));$('resources').append(a);}if(!$('resources').children.length)$('resources').append(el('p','这里没有开放的采集资源。','muted'));
 $('people').replaceChildren();for(const [key,n] of Object.entries(people).filter(([key])=>npcPlace(s,key)===s.place)){const row=el('article','');row.append(el('h3',n.name+' · '+n.role),el('p',(n.age+Math.floor((s.day-1)/360))+'岁；关系'+s.relations[key]+'/100。','muted'),button('与'+n.name+'交谈',()=>talk(s,key),!!blocked));$('people').append(row);}if(!$('people').children.length)$('people').append(el('p','熟悉的当地人此刻不在这里。','muted'));
 $('profile').replaceChildren(el('p',`${s.name} · ${s.gender} · ${s.age+Math.floor((s.day-1)/360)}岁 · ${s.background} · ${s.personality}`),el('p',talents[s.talent].name+'：'+talents[s.talent].text),el('p','起初所有技能为0，没有隐藏身份。'));$('skills').replaceChildren(...Object.entries(skills).map(([key,name])=>{const v=progress(s.skills[key]);return el('p',`${name} Lv${v.level}：${v.xp}/${v.cap}${s.skills[key]===MAX?'【完成】':''}`);}));
 $('inventory').replaceChildren(...Object.entries(items).filter(([key])=>s.bag[key]>0).map(([key,name])=>el('p',name+'×'+s.bag[key])));if(!$('inventory').children.length)$('inventory').append(el('p','目前没有物品。'));$('use-items').replaceChildren(action('eat','吃干粮','15分钟，精力最多+12、气血最多+5'),action('heal','使用常见药材','15分钟，气血最多+20'));
 $('market').replaceChildren();const m=markets[s.place];if(m){$('market').append(el('p',`营业${m.open/60}:00–${m.close/60}:00；每笔15分钟 / 精力1，不能完成则整笔取消。`));for(const type of ['buy','sell']){const grid=el('div','','grid');for(const [key,price] of Object.entries(m[type]))grid.append(button((type==='buy'?'买':'卖')+items[key]+' · '+price+'文',()=>trade(s,type,key),!!blocked||(type==='buy'?s.coins<price:s.bag[key]<1)));$('market').append(grid);}}else $('market').append(el('p','到县城街市或柳溪集交易。','muted'));
 $('recipes').replaceChildren();if(s.place==='workshop'){for(const [id,d] of Object.entries(recipes))$('recipes').append(el('p',d.name+'：'+Object.entries(d.input).map(([k,n])=>items[k]+'×'+n).join('、')+' → '+Object.entries(d.output).map(([k,n])=>items[k]+'×'+n).join('、')),action(id,d.name,`${d.minutes}分钟 / 精力${d.energy}`));}else $('recipes').append(el('p','作坊街可以加工干粮与普通铁料。','muted'));
 $('news').replaceChildren(...(s.news.length?s.news:['尚未跨日；世界新闻将在一天结束后出现。']).map(t=>el('p',t)));const tasks=s.dead?['人生已结束，可导出记录。']:['可到县城或码头做白天短工；也可继续探索。'];if(!s.dead){for(const [key,d] of Object.entries(resources))if(!d.tool||s.bag[d.tool]){const next=d.places.find(place=>s.nodes[place+':'+key].left>0);if(next)tasks.push('可去'+places[next].name+d.name+'，是否参与由你决定。');}if(s.energy<30)tasks.unshift('精力偏低，先歇息或去河湾村借宿。');if(s.hp<50)tasks.unshift('伤势需要恢复，可使用药材或找沈医者。');if(s.bag.ore>=2&&s.bag.wood)tasks.push('原料够用，可去作坊炼制铁料。');} $('tomorrow').replaceChildren(...tasks.map(t=>el('p',t)));$('journal').replaceChildren(...s.journal.map(j=>el('p','第'+j.day+'日：'+j.text)));for(const v of document.querySelectorAll('.view'))v.hidden=v.id!==view;
}
$('command-form').onsubmit=e=>{e.preventDefault();if(!state)return;command(state,$('command-input').value);persist();render();feedback();if(state.pending||state.combat||state.dead){tab('world');$('scene').scrollIntoView({block:'start'});}};
$('create').onsubmit=e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.target));state=fresh(p);view='world';persist();render();tab('world');};
for(const b of $('tabs').children)b.onclick=()=>tab(b.dataset.tab);$('dismiss').onclick=()=>{$('feedback').hidden=true;};$('save').onclick=()=>{persist();};
$('new').onclick=()=>{if(!confirm('开始新的人生将替换青河县当前存档。需要时先导出。'))return;try{localStorage.removeItem(KEY);state=null;$('game').hidden=true;$('setup').hidden=false;}catch(e){$('save-status').textContent='无法清除存档：'+e.message;}};
$('export').onclick=()=>{if(!state)return;const url=URL.createObjectURL(new Blob([JSON.stringify(state)],{type:'application/json'})),a=el('a','');a.href=url;a.download='qinghe-day'+state.day+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onchange=async e=>{const f=e.target.files?.[0];try{if(!f)return;if(f.size>150000)throw Error('存档过大。');const raw=await f.text();const {restore}=await import('./engine.js?v=0.1.0'),candidate=restore(raw);if(!confirm(`导入${candidate.name}，第${candidate.day}日，${candidate.coins}文？将替换青河县当前进度。`))return;state=importSave(raw,state);view='world';render();tab('world');$('save-status').textContent='导入成功。';}catch(err){$('save-status').textContent='导入未完成：'+err.message;}finally{e.target.value='';}};
try{state=load();if(state){render();tab('world');}}catch(e){$('startup-error').textContent='存档未能读取，原始记录没有被覆盖：'+e.message;}
if(globalThis.navigator?.serviceWorker)navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(reg=>{const worker=reg.installing||reg.waiting||reg.active;if(!worker){$('offline').textContent='离线文件尚未就绪。';return;}const status=()=>{$('offline').textContent=worker.state==='activated'?'青河县离线文件已就绪。':worker.state==='redundant'?'离线准备失败，可继续联网玩。':'正在准备青河县离线文件，首次请保持联网。';};worker.addEventListener('statechange',status);status();}).catch(()=>{$('offline').textContent='离线准备失败，可继续联网玩。';});else $('offline').textContent='此浏览器可联网玩，未提供离线缓存。';
