import {places,items,skills,resources,nodeDefs,recipes,markets,people,talents} from './content.js?v=0.1.0';
import {gain,progress,MAX} from './progression.js?v=0.1.0';
import {advance,random,npcPlace} from './world.js?v=0.1.0';
export const KEY='jianghu-qinghe-county-v1';
export function fresh(p={}){return {version:'county-1',name:String(p.name||'无名客').trim().slice(0,12)||'无名客',age:Math.max(16,Math.min(60,Math.floor(Number(p.age)||18))),gender:p.gender==='女'?'女':'男',background:['农家','学徒','小贩'].includes(p.background)?p.background:'农家',personality:['谨慎','随和','勤奋'].includes(p.personality)?p.personality:'谨慎',talent:Object.hasOwn(talents,p.talent)?p.talent:'ordinary',day:1,minute:480,place:'county',weather:'晴',coins:30,hp:100,energy:100,dead:false,seed:823471,bag:Object.fromEntries(Object.keys(items).map(k=>[k,k==='food'?2:0])),skills:Object.fromEntries(Object.keys(skills).map(k=>[k,0])),relations:Object.fromEntries(Object.keys(people).map(k=>[k,0])),talkDays:{},nodes:Object.fromEntries(Object.entries(nodeDefs).map(([k,n])=>[k,{left:n.capacity,refreshDay:3}])),encounterDay:0,pending:null,combat:null,news:[],journal:[],result:['你是初到青河县的普通人。可以找活、认识当地人，也可以自行出门。']};}
const fail=(s,t)=>{s.result=[t];return false;},sign=n=>(n>=0?'+':'')+n;
function available(s){if(s.dead)return fail(s,'这段人生已经结束，不会自动读档。');if(s.pending||s.combat)return fail(s,'先处理眼前选择或交手，也可以离开。');return true;}
export function cost(s,n){return Math.max(0,n-(s.talent==='enduring'?2:0));}
function settle(s,title,minutes,energy,run,xp={}){if(s.energy<energy)return fail(s,'精力不足，先歇息。');const b=structuredClone(s),fatigue=s.energy-energy<20; s.result=[];run();s.energy=Math.max(0,s.energy-energy);advance(s,minutes);s.result.unshift(title,`精力：${b.energy} → ${s.energy}（${sign(s.energy-b.energy)}）`,`金钱：${b.coins} → ${s.coins}（${sign(s.coins-b.coins)}文）`);if(b.hp!==s.hp)s.result.push(`气血：${b.hp} → ${s.hp}（${sign(s.hp-b.hp)}）`);for(const [k,n] of Object.entries(xp)){const line=gain(s,k,Math.max(1,Math.floor(n*(fatigue?.5:1))));if(line)s.result.push(line);}for(const [k,n] of Object.entries(items))if(s.bag[k]!==b.bag[k])s.result.push(`${n}：${b.bag[k]} → ${s.bag[k]}（${sign(s.bag[k]-b.bag[k])}）`);if(s.energy<20)s.result.push(s.energy<10?'极疲：采集与交手效率降低。':'疲惫：采集与成长效率降低。');s.journal=[{day:s.day,text:s.result.join('；')},...s.journal].slice(0,30);return true;}
export function move(s,to,rng=()=>random(s)){if(!available(s))return false;if(!places[s.place].routes.includes(to))return fail(s,'这里没有直达的路，请按地图分段走。');const outdoor=places[to].area!=='县城与近郊'||to==='road',minutes=places[to].minutes+(s.weather==='雨'&&outdoor?15:0);return settle(s,'前往'+places[to].name,minutes,0,()=>{s.place=to;if(to==='oldroad'&&s.encounterDay!==s.day){s.encounterDay=s.day;if(rng()<.25){s.pending={type:'bandit'};s.result.push('拦路人出现：可以绕行半小时或交手，实战可能致命。');}else s.result.push('旧道暂时安静，今天没有遇到拦路人。');}});}
export function chance(s,d){return Math.min(.95,d.chance+(progress(s.skills[d.skill]).level-1)*.02+(s.talent==='observant'?.03:0)-(s.weather==='雨'?.1:0))*(s.energy-cost(s,d.energy)<20?.75:1);}
export function resourceBlocker(s,key){const d=resources[key],node=s.nodes[s.place+':'+key];if(!d||!node)return '这里没有这项资源。';if(s.hp<25)return '伤势太重，先治疗再采集。';if(key==='vegetables'&&(s.minute<360||s.minute+d.minutes>1080))return '余菜分拣需在农户06:00–18:00内完成。';if(node.left<=0)return '本处已经暂时采尽，第'+node.refreshDay+'日恢复。';if(d.tool&&!s.bag[d.tool])return '需要'+items[d.tool]+'，工具可重复使用。';if(s.energy<cost(s,d.energy))return '精力不足，先休息。';return null;}
function gather(s,key,rng){const d=resources[key],why=resourceBlocker(s,key);if(why)return fail(s,why);const success=rng()<chance(s,d);return settle(s,d.name,d.minutes,cost(s,d.energy),()=>{s.nodes[s.place+':'+key].left--;s.pending=null;if(success){for(const [k,n] of Object.entries(d.output))s.bag[k]+=n;s.result.push('本次收获：'+Object.entries(d.output).map(([k,n])=>items[k]+'×'+n).join('、'));}else s.result.push('这次没有找到合用资源，时间与精力已付出。');if(d.risk&&rng()<d.risk){s.hp-=d.damage;s.result.push('擦伤'+d.damage+'点气血，需要恢复。');}s.result.push('本资源点每两日恢复，离开再进入不会刷新。');},{[d.skill]:success?2:1});}
export function trade(s,type,key,n=1){if(!available(s))return false;const m=markets[s.place];if(!m||s.minute<m.open||s.minute+15>m.close)return fail(s,'此处商铺未营业或已来不及成交。');if(!['buy','sell'].includes(type)||!Number.isInteger(n)||n<1||n>20)return fail(s,'交易数量需为1–20的整数。');const price=m[type][key];if(price===undefined)return fail(s,'这里不经营这件物品。');if(type==='buy'&&s.coins<price*n||type==='sell'&&s.bag[key]<n)return fail(s,'钱或库存不足，整笔未成交。');return settle(s,(type==='buy'?'购买':'出售')+items[key]+'×'+n,15,1,()=>{s.coins+=(type==='buy'?-1:1)*price*n;s.bag[key]+=(type==='buy'?1:-1)*n;s.result.push('单价'+price+'文，总价'+price*n+'文。');},type==='sell'?{trade:1}:{});}
export function talk(s,key){if(!available(s))return false;if(!Object.hasOwn(people,key)||npcPlace(s,key)!==s.place)return fail(s,'此人目前不在这里。');return settle(s,'与'+people[key].name+'交谈',30,1,()=>{s.result.push(people[key].line);if(s.talkDays[key]!==s.day){const b=s.relations[key];s.relations[key]=Math.min(100,b+1);s.talkDays[key]=s.day;s.result.push(`关系：${b}/100 → ${s.relations[key]}/100（+${s.relations[key]-b}）`);}else s.result.push('今日已经聊过，不重复增加关系。');});}
export function act(s,id,rng=()=>random(s)){
 if(!available(s))return false;
 if(Object.hasOwn(resources,id)){const why=resourceBlocker(s,id);if(why)return fail(s,why);const d=resources[id];if(d.risk){s.pending={type:'resource',key:id};s.result=['确认危险采集：'+d.name,`有${d.risk*100}%擦伤${d.damage}点气血的风险，可以不参与；尚未扣精力或时间。`];return true;}return gather(s,id,rng);}
 if(id==='work'){if(!places[s.place].work)return fail(s,'这里没有普通短工。');if(s.hp<25)return fail(s,'先养伤，再做重活。');const open=s.place==='fields'||s.place==='dock'?360:420,close=1080;if(s.minute<open||s.minute+180>close)return fail(s,'短工需在白天营业时段内做完3小时。');return settle(s,'做完一份短工',180,cost(s,24),()=>{s.coins+=12;s.result.push('雇主支付12文，没有隐藏任务。');},{[s.place==='fields'?'farming':'carry']:2});}
 if(id==='rest')return settle(s,'歇息',120,0,()=>{s.energy=Math.min(100,s.energy+30);s.hp=Math.min(100,s.hp+10);});
 if(id==='wait')return settle(s,'等候半小时',30,0,()=>{s.result.push('等候不恢复精力或气血。');});
 if(id==='sleep'){if(!['inn','village'].includes(s.place))return fail(s,'可到客栈住宿或河湾村借宿。');const fee=s.place==='inn'?5:0;if(s.coins<fee)return fail(s,'住宿需要5文。');return settle(s,'睡一觉',480,0,()=>{s.coins-=fee;s.energy=100;s.hp=Math.min(100,s.hp+20);});}
 if(id==='eat'||id==='heal'){const key=id==='eat'?'food':'herb';if(!s.bag[key])return fail(s,'没有'+items[key]+'。');if(s.hp===100&&(id==='heal'||s.energy===100))return fail(s,'现在不需要恢复，不消耗物品。');return settle(s,id==='eat'?'吃干粮':'用常见药材处理伤口',15,0,()=>{s.bag[key]--;s.hp=Math.min(100,s.hp+(id==='eat'?5:20));if(id==='eat')s.energy=Math.min(100,s.energy+12);});}
 if(id==='doctor'){if(s.place!=='village'||s.minute<480||s.minute+60>1080)return fail(s,'请在河湾村08:00–18:00内完成诊治，共1小时。');if(s.hp===100)return fail(s,'无需治疗。');if(s.coins<8)return fail(s,'诊金8文，不足则不治疗。');return settle(s,'医者治疗',60,0,()=>{s.coins-=8;s.hp=Math.min(100,s.hp+50);});}
 if(id==='train'){if(s.place!=='school'||s.minute<480||s.minute+120>1080)return fail(s,'请在武馆08:00–18:00内完成基础练习，共2小时。');if(s.hp<25)return fail(s,'先养伤。');return settle(s,'练习入门拳脚',120,18,()=>{s.result.push('仅为入门练习，完整武学成长将在后续系统批次开放。');},{fist:2});}
 if(Object.hasOwn(recipes,id)){const d=recipes[id];if(s.place!=='workshop'||s.minute<420||s.minute+d.minutes>1080)return fail(s,'请在作坊07:00–18:00内完成加工。');for(const [k,n] of Object.entries(d.input))if(s.bag[k]<n)return fail(s,items[k]+'不足，未消耗材料。');return settle(s,d.name,d.minutes,d.energy,()=>{for(const [k,n] of Object.entries(d.input))s.bag[k]-=n;for(const [k,n] of Object.entries(d.output))s.bag[k]+=n;s.result.push('本次生产：'+Object.entries(d.output).map(([k,n])=>items[k]+'×'+n).join('、'),'材料消耗：'+Object.entries(d.input).map(([k,n])=>items[k]+' -'+n).join('、'),'当前库存：'+Object.keys(d.input).map(k=>items[k]+' '+s.bag[k]).join('、'));},{[d.skill]:2});}
 return fail(s,'这项行动尚未实装。');
}
export function choose(s,id,rng=()=>random(s)){if(s.dead||!s.pending)return fail(s,'没有待决定的事情。');if(s.pending.type==='resource'){if(id==='leave'){s.pending=null;s.result=['你没有进行危险采集，时间、精力和库存未变。'];return true;}if(id==='gather')return gather(s,s.pending.key,rng);return fail(s,'请选择采集或离开。');}if(!['avoid','fight'].includes(id))return fail(s,'请选择绕开或交手。');return settle(s,id==='avoid'?'绕开拦路人':'迎战拦路人',id==='avoid'?30:1,0,()=>{s.pending=null;if(id==='fight'){s.combat={hp:28};s.result.push('实战可能死亡，可随时撤离。');}});}
export function fight(s,id,rng=()=>random(s)){if(s.dead||!s.combat)return fail(s,'当前没有交手。');if(!['attack','heavy','guard','flee'].includes(id))return fail(s,'未知招式。');const en=id==='flee'?Math.min(2,s.energy):id==='heavy'?8:4;return settle(s,id==='flee'?'撤离':id==='guard'?'防守':id==='heavy'?'重击':'出拳',1,en,()=>{if(id==='flee'){s.combat=null;s.result.push('你保住性命退开了。');return;}if(id!=='guard'){const hit=id==='attack'||rng()<.7,damage=(id==='heavy'?10:6)+Math.min(4,progress(s.skills.fist).level-1);if(hit){s.combat.hp-=Math.max(1,damage-(s.energy-en<20?2:0));s.result.push('你击中对手。');}else s.result.push('重击落空。');}if(s.combat.hp<=0){s.combat=null;s.coins+=4;s.result.push('拦路人逃走，追回4文钱；没有额外经验或装备。');return;}const harm=id==='guard'?1:6;s.hp=Math.max(0,s.hp-harm);s.result.push('受到'+harm+'点伤害。');if(!s.hp){s.dead=true;s.combat=null;s.result.push('你伤重死去，这段人生结束，不会自动读档。');}},{...(id==='attack'||id==='heavy'?{fist:1}:{}),...(id==='flee'?{}:{battle:1})});}
export function restore(raw){const s=JSON.parse(raw),int=(n,a,b)=>Number.isSafeInteger(n)&&n>=a&&n<=b,obj=x=>x&&typeof x==='object'&&!Array.isArray(x);if(!obj(s)||s.version!=='county-1')throw Error('不是青河县独立存档。');if(typeof s.name!=='string'||!s.name.trim()||s.name.length>12||!int(s.age,16,60)||!['男','女'].includes(s.gender)||!['农家','学徒','小贩'].includes(s.background)||!['谨慎','随和','勤奋'].includes(s.personality)||!Object.hasOwn(talents,s.talent))throw Error('人物资料无效。');for(const [k,a,b] of [['day',1,100000],['minute',0,1439],['hp',0,100],['energy',0,100],['coins',0,10000000],['seed',1,4294967295],['encounterDay',0,s.day]])if(!int(s[k],a,b))throw Error('数值无效。');if(!Object.hasOwn(places,s.place)||!['晴','雨'].includes(s.weather)||typeof s.dead!=='boolean'||s.dead!==(s.hp===0))throw Error('世界状态无效。');for(const [map,keys,max] of [[s.bag,Object.keys(items),1000000],[s.skills,Object.keys(skills),MAX],[s.relations,Object.keys(people),100]]){if(!obj(map))throw Error('记录无效。');for(const k of keys)if(!int(map[k],0,max))throw Error('库存或成长无效。');}if(!obj(s.talkDays)||Object.entries(s.talkDays).some(([k,v])=>!Object.hasOwn(people,k)||!int(v,1,s.day)))throw Error('交谈记录无效。');if(!obj(s.nodes)||Object.keys(s.nodes).length!==Object.keys(nodeDefs).length)throw Error('资源点无效。');for(const [k,d] of Object.entries(nodeDefs)){const n=s.nodes[k];if(!obj(n)||!int(n.left,0,d.capacity)||!int(n.refreshDay,s.day+1,s.day+2)||n.refreshDay%2!==1)throw Error('资源记录无效。');}if(s.pending&&!(s.pending.type==='bandit'&&s.place==='oldroad'||s.pending.type==='resource'&&Object.hasOwn(resources,s.pending.key)&&!!s.nodes[s.place+':'+s.pending.key]&&resources[s.pending.key].risk>0))throw Error('选择无效。');if(s.combat&&(!obj(s.combat)||!int(s.combat.hp,1,28)||s.place!=='oldroad'))throw Error('战斗无效。');if(s.combat&&s.pending||s.dead&&(s.pending||s.combat))throw Error('状态冲突。');for(const k of ['news','result'])if(!Array.isArray(s[k])||s[k].length>(k==='news'?20:100)||s[k].some(x=>typeof x!=='string'||x.length>3000))throw Error('消息无效。');if(!Array.isArray(s.journal)||s.journal.length>30||s.journal.some(x=>!obj(x)||!int(x.day,1,s.day)||typeof x.text!=='string'||x.text.length>10000))throw Error('日志无效。');return s;}
