// 内容与规则分开：全部事件、人物和行动均来自代码，不使用生成式剧情。
export const locations={
 liuxi:{board:true,name:'柳溪集',tag:'外地集市 · 带货与采购',text:'集旁有一间小武馆，陆教习08:00–18:00教授普通剑棍。柳树下的小集与青石镇各有行情。铁制工具在此卖21文、鲜鱼7文、蔬菜3文；先算好买料和路程，再决定带什么货。可走旧渡口的河岸路，也可经竹林来往。',routes:['ferry','bamboo'],actions:['browse']},
 ferry:{name:'旧渡口',tag:'河岸 · 护送与邻人',text:'摆渡的小舟搁在岸边，沿岸步道通往青石码头和柳溪集。走这条步道不收船费，不会强制遇敌；可以钓鱼、找活，也可以只看河水。',routes:['dock','liuxi'],actions:['work','fish','browse']},
 town:{board:true,name:'青石镇',tag:'街市 · 买卖与接活',text:'石板路两旁是粮铺和茶摊。有人赶集，有人找活，也有人只是坐着听闲话。',routes:['inn','forge','dock','village','road'],actions:['work','browse']},
 inn:{name:'长安客栈',tag:'歇脚 · 消息与人物',text:'窗边的旅人喝着茶，店小二收拾空碗。周师傅收工后常来这里歇脚。',routes:['town'],actions:['sleep','browse']},
 forge:{name:'周记作坊',tag:'手艺 · 打造与烹饪',text:'炉边摆着铁料和木柄。这里接小件农具的活，手艺可以从最普通的一把锄头练起。',routes:['town'],actions:['forge','cook','cookMeat','cookVegetables','smelt','craftStaff','craftSword','craftTrap']},
 dock:{name:'青石码头',tag:'谋生 · 搬货与钓鱼',text:'船工吆喝着卸货，河岸边也有安静的钓位。靠力气和耐心，都能谋一份生活。',routes:['town','village','ferry'],actions:['work','fish']},
 village:{name:'河湾村',tag:'邻里 · 采药与休养',text:'田埂穿过村舍，沈医者在院中晾药。村民愿意让过路人借宿，药炉也能借用；先向沈医者学习基础制药。',routes:['town','dock','hill'],actions:['gather','sleep','brew','plant','tend','harvest']},
 road:{name:'城外小路',tag:'江湖 · 练拳与探索',text:'周师傅白日在树荫下教拳。再往远处走，便是行脚人和商队经过的竹林。',routes:['town','hill','bamboo'],actions:['train','explore']},
 hill:{name:'南山坡',tag:'野外 · 草药与行路',text:'山风吹过草丛，旧道绕向竹林。草药不会处处都有，旧矿点可采矿，草丛间可用简易猎具捕猎，也可以只是看看路。',routes:['village','road','bamboo'],actions:['gather','mine','hunt','explore']},
 bamboo:{name:'竹林',tag:'野外 · 练武与偶遇',text:'竹影落在土路上，脚步声在林间格外清楚。这里适合练拳，也能捡拾落枝整理木料，遇事可以转身离开。',routes:['road','hill','liuxi'],actions:['train','gather','collectWood','explore']}
};
export const skills={steadySword:'平川剑法',shelterStaff:'护身棍法',fist:'拳脚',inner:'吐纳',carry:'搬运',herb:'采药',forge:'锻造',cook:'烹饪',trade:'经商',fish:'钓鱼',staff:'棍法',sword:'剑术',forage:'采集',mining:'采矿',woodwork:'木工',medicine:'制药',hunt:'狩猎',farming:'农耕',escort:'护送',battle:'临战判断'};
export const items={food:'干粮',herb:'草药',iron:'铁料',wood:'木料',tool:'铁制工具',fish:'鲜鱼',rod:'钓竿',staff:'木棍',sword:'普通铁剑',ore:'铁矿石',salve:'普通药膏',trap:'简易猎具',meat:'猎物肉',seed:'菜种',vegetable:'蔬菜'};
export const people={tutor:{gift:'food',name:'陆教习',role:'柳溪武馆教习',personality:'严谨',interest:'基础剑棍与扎实步法',goal:'教好普通剑棍，让学徒懂得何时进、何时守',line:'基础扎实，再学一门普通武艺。招式各有所长，练熟要花时间，考较也不是天下排名。'},
 qiao:{gift:'vegetable',name:'乔掌柜',role:'柳溪集商贩',personality:'精细',interest:'常用农具与菜蔬',goal:'收齐集上农户要用的工具，做稳当的小买卖',line:'镇上与集上各有价，差价不是白来的钱。算上路程，再看这一趟值不值得。'},
 boatman:{gift:'wood',name:'贺船工',role:'旧渡口船工',personality:'厚道',interest:'河岸道路与修船手艺',goal:'把靠岸小舟的系泊木桩整好，收工后回集上歇脚',line:'沿岸走就能到码头，不必花船钱。护送货物先认交接点，遇事也可以放下这份活。'},
 artisan:{gift:'iron',name:'许铁匠',role:'作坊铁匠',personality:'务实',interest:'炉火与农具',goal:'把农具做好，也教新手学会基本手艺',line:'先学会看火色和落锤，再想打什么名剑。普通农具做结实了，也是一门饭碗。'},
 master:{gift:'food',name:'周师傅',role:'基础武艺师傅',personality:'直爽',interest:'习武与喝茶',goal:'把基础拳脚、棍法与剑术教给肯下功夫的人',line:'学拳是为了站稳脚跟，能不打的时候，也要懂得不打。'},
 merchant:{gift:'fish',name:'柳掌柜',role:'街市商人',personality:'精明',interest:'各地货价',goal:'把小铺经营好',line:'做买卖先从一两件货开始，赔得起，才学得会。'},
 doctor:{gift:'herb',name:'沈医者',role:'乡村医者',personality:'温和',interest:'草药与乡邻',goal:'收齐本月常用的药材',line:'山上寻药也要量力，受了伤就别硬撑。'},
 porter:{gift:'food',name:'阿平',role:'码头脚夫',personality:'随和',interest:'船上的见闻',goal:'攒钱修一修家里的屋顶',line:'码头有活就做，没活的时候，我也会钓两条鱼。'}
};
export const npcSchedules={tutor:{place:'liuxi',from:8,to:18,off:'liuxi'},qiao:{place:'liuxi',from:8,to:18,off:'liuxi'},boatman:{place:'ferry',from:6,to:18,off:'liuxi'},master:{place:'road',from:7,to:18,off:'inn'},merchant:{place:'town',from:8,to:20,off:'inn'},doctor:{place:'village',from:8,to:18,off:'inn'},artisan:{place:'forge',from:7,to:18,off:'inn'},porter:{place:'dock',from:6,to:18,off:'inn'}};
export const jobs={
 smithBatch:{career:'smith',name:'工具批单',place:'forge',needs:{tool:3},reward:72,skill:'trade',text:'铁匠试作验收后开放，三日内交工具3件收72文；自备材料，每日最多一份。交货半小时、精力2，不因交付增加锻造经验。'},
 clinicBatch:{career:'healer',name:'诊所配药',place:'village',needs:{herb:3,wood:2},hours:1,energy:10,shift:[8,18],reward:28,skill:'medicine',text:'医者帮手验收后开放；自备草药3份、木料2份，在村里08:00–18:00内调制药膏3份交诊所，1小时、精力10、报酬28文、制药经验+2，每日最多一份。成品交给诊所，不进入背包。',result:'本次调制：普通药膏3份，已交给诊所，不进入背包。诊所支付28文，原料已经实际消耗。'},
 skilledLoading:{career:'boat',name:'熟手装船',place:'dock',hours:2,energy:16,reward:18,skill:'carry',shift:[6,18],text:'熟练船工确认后开放，青石码头06:00–18:00内做完2小时搬货，精力16、工钱18文、搬运经验+2；每日最多一份。'} ,
 urgentTool:{varied:true,name:'急用农具',place:'forge',days:0,needs:{tool:1},reward:30,skill:'trade',text:'今日结束前把铁制工具1件送到作坊，报酬30文，每日最多一份。可交库存、自己打造或在青石镇花20文买一件（按此买价净赚10文）；交货半小时、精力2，制作成本另算。超时失去本单报酬，不罚款。'},
 merchantCargo:{varied:true,name:'商人带货',start:'town',place:'liuxi',needs:{food:3},reward:20,skill:'trade',text:'在青石镇接单，自己备干粮3份，三日内带到柳溪集交付20文。青石镇单价4文，买3份成本12文、按该买价净赚8文；也可用自己已有或制作的干粮，不预付本金。交货半小时、精力2，每日一份。'},
 escortTraveler:{varied:true,name:'护送行脚人',start:'town',place:'liuxi',routes:{short:['road','bamboo','liuxi'],river:['village','dock','ferry','liuxi']},routeNames:{short:'竹林短路',river:'河岸长路'},riskPlace:'bamboo',riskChance:0.3,traveler:true,energy:6,reward:20,xp:{escort:2,carry:1},relationReward:{person:'qiao',amount:2},text:'青石镇接单，三日内护送行脚人到柳溪集。先自行选择竹林短路或河岸长路，途中不能悄悄换路线。竹林交接点有30%概率遇拦路人，可绕行半小时、交手或撤离，不要求获胜。河岸长路无本单安排的拦路风险，但普通世界事件照常。交付半小时、精力6，工钱20文、乔掌柜关系+2，每日一份。'},
 liuxiTools:{board:'liuxi',name:'柳溪集收农具',place:'liuxi',needs:{tool:1},reward:26,skill:'trade',text:'乔掌柜为农户收铁制工具1件，三日内送到柳溪集，报酬26文。每日最多一份，材料或货物自备；普通出售工具仍为21文。'},
 ferryParcel:{board:'liuxi',name:'沿岸护送货包',start:'liuxi',place:'dock',route:['ferry','dock'],energy:6,reward:12,xp:{escort:1,carry:1},cargo:'封好货包',text:'在柳溪集领封好的普通货包，沿旧渡口、青石码头顺序交接，三日内完成；步行不收船费、不耗精力，最终交付半小时、精力6，报酬12文。途中事情可忽略，没有必打战斗。'},
 repairTools:{name:'农具修理',place:'forge',partner:'artisan',relation:5,requires:{forge:2},hours:1,energy:12,shift:[7,18],needs:{iron:1,wood:1},reward:18,xp:{forge:2,woodwork:1},text:'许铁匠介绍一份修理活：修整农具刃口、更换木柄。需锻造Lv2、关系5，自备铁料1、木料1；作坊提供锤具。一小时、精力12，07:00–18:00内完成，工钱18文，每日最多一份。修好的农具归委托人。',result:'本次完成：修复农具1件，已交还委托人，不进入背包。你修整刃口并加工木柄，收到18文工钱。'},
 artisanSupply:{name:'铁匠农具补货',place:'forge',partner:'artisan',relation:5,requires:{forge:2},needs:{tool:2},reward:44,skill:'trade',text:'许铁匠愿向熟悉的手艺人收购铁制工具2件，三日内送到作坊；需锻造Lv2、关系5。用现有库存交付也可以，报酬44文，每日最多一份。'},
 doctorSupply:{name:'医者药膏补货',place:'village',partner:'doctor',relation:5,requires:{medicine:2},needs:{salve:2},reward:16,skill:'trade',text:'沈医者向熟悉的制药人收普通药膏2份，三日内送到河湾村；需制药Lv2、关系5。报酬16文，每日最多一份，不预付材料。'},
 merchantSupply:{name:'商人干粮补货',place:'town',partner:'merchant',relation:5,requires:{cook:2},needs:{food:4},reward:18,skill:'trade',text:'柳掌柜向熟悉的厨人收干粮4份，三日内送到街市；需烹饪Lv2、关系5。报酬18文，每日最多一份，交货不会额外增加烹饪经验。'},
 fieldWork:{name:'田间短工',place:'village',text:'帮村民整地除草，雇主提供工具；三小时、精力24，工钱12文。06:00–18:00内完成，每日一份。',hours:3,energy:24,reward:12,skill:'farming',shift:[6,18]},
 smithWork:{name:'作坊短工',place:'forge',text:'需锻造Lv2，帮作坊加工小件农具，雇主提供材料工具，成品归作坊；三小时、精力24，工钱16文。07:00–18:00内完成，每日一份。',hours:3,energy:24,reward:16,skill:'forge',requires:{forge:2},shift:[7,18]},
 escortMedicine:{name:'短途护送药包',start:'town',place:'village',route:['road','hill','village'],text:'从街市领取封好的药包，沿城外小路、南山坡送到河湾村。按顺序经过交接点，三日内交付；途中遇事可以自行处理或放弃。交付半小时、精力6，报酬10文。',energy:6,reward:10,xp:{escort:1,carry:1}},
 firewood:{name:'村里收柴',place:'village',text:'村民需要木料3份生火，可拾柴整理或买来，三日内送到河湾村。',needs:{wood:3},reward:8,skill:'trade',boardDay:0},
 freshFish:{name:'船家收鱼',place:'dock',text:'船家需要鲜鱼2条做饭，三日内送到码头。',needs:{fish:2},reward:12,skill:'trade',boardDay:1},
 oreSupply:{name:'作坊收矿',place:'forge',text:'作坊收铁矿石2份，三日内送来；无需先炼成铁料。',needs:{ore:2},reward:10,skill:'trade',boardDay:2},
 unload:{name:'码头卸货',place:'dock',text:'替船行卸一批货，靠力气赚一笔工钱。',hours:3,energy:24,reward:18,skill:'carry'},
 tools:{name:'一件农具',place:'forge',text:'作坊需要一件铁制工具；自己备料制作，再交货。',needs:{tool:1},reward:22,skill:'trade'},
 herbs:{name:'医者收药',place:'village',text:'给沈医者送两份草药，采来的或买来的都可以。',needs:{herb:2},reward:12,skill:'trade'}
};
export const recipes={cookVegetables:{name:'做菜饭干粮',hours:1,energy:8,input:{vegetable:2,wood:1},output:{food:2},skill:'cook'},craftTrap:{name:'制作简易猎具',hours:2,energy:14,input:{wood:2,iron:1},output:{trap:1},skill:'woodwork'},cookMeat:{name:'做烤肉干粮',hours:1,energy:8,input:{meat:1,wood:1},output:{food:2},skill:'cook'},brew:{name:'调制普通药膏',place:'village',hours:1,energy:10,input:{herb:2,wood:1},output:{salve:2},skill:'medicine',knowledge:'learnedMedicine'},craftStaff:{name:'制作木棍',hours:2,energy:14,input:{wood:2},output:{staff:1},skill:'woodwork'},craftSword:{name:'锻造普通铁剑',hours:4,energy:32,input:{iron:4,wood:1},output:{sword:1},skill:'forge',level:2},smelt:{name:'炼制铁料',hours:2,energy:18,input:{ore:2,wood:2},output:{iron:2},skill:'forge'},forge:{name:'打造工具',hours:3,energy:24,input:{iron:2,wood:1},output:{tool:1},skill:'forge'},cook:{name:'做一份鱼饭',hours:1,energy:8,input:{fish:1,wood:1},output:{food:2},skill:'cook'}};
export const actionNames={buyHome:'购买镇上旧屋',assessment:'基础武艺考较',forgeLesson:'请教基础锻造',plant:'借地播种',tend:'照料菜地',harvest:'收获蔬菜',cookVegetables:'做菜饭干粮',hunt:'布置猎具捕猎',craftTrap:'制作简易猎具',cookMeat:'做烤肉干粮',brew:'调制普通药膏',useSalve:'使用普通药膏',craftStaff:'制作木棍',craftSword:'锻造普通铁剑',collectWood:'拾柴整理木料',mine:'浅层采矿',smelt:'炼制铁料',work:'打零工',browse:'听街谈',train:'练习拳脚',inner:'吐纳修炼',gather:'采药',fish:'钓鱼',forge:'打造工具',cook:'做鱼饭',rest:'歇息片刻',sleep:'睡一觉',eat:'吃干粮',heal:'用草药',treat:'请医者治疗',explore:'沿路探索',spar:'请教切磋',deliver:'完成约定'};
export const events={
 boatThanks:{title:'修船人的回信',place:'dock',text:'先前补好的船已经跑完一趟。船工留下一份干粮谢你，请你自行决定是否领取；没有后续任务。',choices:[{id:'take',label:'领船工留下的干粮1份',output:{food:1},hours:0.25,energy:0,result:'你收到干粮1份。这件小事到此结束，不增加技能经验。'},{id:'leave',label:'谢过，不领取',result:'你谢过船工，没有拿走回礼。'}],after:'船工收起无人领取的干粮，继续跑船。'},
 herbThanks:{title:'沈医者留了药草',place:'village',text:'前些天收进屋的药草已经晾好。沈医者留了草药1份感谢你的帮助，可自行领取，不必再接差事。',choices:[{id:'take',label:'领草药1份',output:{herb:1},hours:0.25,energy:0,result:'你收到草药1份，没有采集或制药，因此不增加相关经验。'},{id:'leave',label:'留给诊所使用',result:'你没有领取，草药留给诊所。'}],after:'沈医者把未领取的草药收回诊所使用。'},
 roofThanks:{title:'阿平的屋顶修好了',place:'dock',text:'阿平的屋顶已经补好。他托人向你道谢，留了一份干粮。不要求你再帮忙，也没有新任务。',choices:[{id:'take',label:'领阿平的干粮1份',output:{food:1},hours:0.25,energy:0,result:'你收到干粮1份，阿平的屋顶小事到此结束。'},{id:'leave',label:'心意领了，干粮留给他',result:'干粮留给阿平，你按自己的安排走。'}],after:'阿平收回未领取的干粮，照常去码头找活。'},
 weeklyMarket:{title:'青石镇赶集日',place:'town',text:'逢七日的小集正在开张，08:00–20:00开放。摊贩提供一次小份集日价：干粮2份6文，或菜种2份4文；每次赶集只能选择一笔，价格和库存真实结算。',choices:[{id:'food',label:'集日买干粮2份，付6文',coins:-6,output:{food:2},hours:0.25,energy:1,result:'本笔成交：干粮2份，总价6文；这次集日购买已结束，不增加买入经验。'},{id:'seed',label:'集日买菜种2份，付4文',coins:-4,output:{seed:2},hours:0.25,energy:1,result:'本笔成交：菜种2份，总价4文；这次集日购买已结束。'},{id:'leave',label:'不买，继续自己的安排',result:'你没有买货，摊贩仍会自行营业。'}],after:'青石镇的小集散了，摊贩收摊回家。'},
 weeklySpar:{title:'武馆公开切磋日',place:'liuxi',text:'武馆今日安排公开切磋，08:00–18:00开放。周师傅过来陪练，不收报名费；需要气血30、精力20，可随时撤离，重伤前会收手。没有奖金或考较通过记录，经验按实际出招结算。',choices:[{id:'spar',label:'参加公开切磋',hours:0.08333333333333333,energy:0,minHp:30,minEnergy:20,combat:true,result:'你自行选择参加点到为止的切磋，随时可以撤离。'},{id:'leave',label:'不参加切磋',result:'其他练武的人照常切磋，你可以走自己的路。'}],after:'武馆公开切磋结束，教习和学徒各自散去。'},
 weeklyDock:{title:'码头集中装船日',place:'dock',text:'码头今日集中装船，临时缺一名帮工；08:00以后开始，18点前做完2小时的活，消耗精力16，工钱14文，搬运经验+1。可以不接，不会背上约定。',choices:[{id:'work',label:'集中装船，收14文',hours:2,energy:16,minHp:25,coins:14,skill:'carry',xp:1,result:'你实际搬完这一批货，领到14文工钱。船队按自己的行程启航。'},{id:'leave',label:'不接临时帮工',result:'领工继续找其他帮工，船队照常安排装船。'}],after:'装船已经由脚行完成，船队离开码头。'},
 boatRepair:{title:'小船的舱板开裂',place:'dock',text:'一艘小船停在码头，船工正在找木料补板，愿付16文请人提供木料并修好。货物已搬上岸，不会因你路过就逼你接手。',choices:[{id:'help',label:'提供木料2并帮忙修板',input:{wood:2},hours:1,energy:12,minHp:25,skill:'woodwork',xp:1,coins:16,result:'你帮船工补好舱板，船行付你16文，补好的船留在码头。'},{id:'tell',label:'替他们问问附近工匠',hours:0.5,energy:2,result:'附近木匠接下了修船的活，船工继续搬货。'},{id:'leave',label:'不参与',result:'船工继续找木料和工匠，你按自己的安排走。'}],after:'码头的小船已由船工请木匠补好舱板，重新装货。'},
 marketPrice:{title:'街市有人争价',place:'town',text:'两位摊贩争论同一批杂货该卖多少钱，买主站在一旁比较。只是普通买卖上的分歧。',choices:[{id:'compare',label:'比较几家报价再听双方说法',hours:1,energy:4,skill:'trade',xp:1,result:'你比较了几家的报价，发现品相和数量并不相同。双方各自定价，买主自己挑选，没有强制成交。'},{id:'leave',label:'不掺和',result:'争价还在继续，你没替别人做买卖上的决定。'}],after:'街市争价的摊贩各自标好了价，买主已经自行挑选货物。'},
 villageMeal:{title:'邻家忙着张罗晚饭',place:'village',text:'一户村民正为帮工的人准备晚饭，灶前人手忙乱，桌边少了一份口粮。旁边邻居也在问能不能帮忙。',choices:[{id:'share',label:'拿出干粮1给他们添一份饭',input:{food:1},hours:0.5,energy:2,result:'你拿出一份干粮，主人道谢后继续准备晚饭。没有额外工钱或技能经验。'},{id:'chat',label:'坐一会儿，听听邻里闲话',hours:0.5,energy:1,result:'你听他们说起屋顶、田地和家里的琐事，随后告辞。只是一次普通往来。'},{id:'leave',label:'不打扰，继续自己的事',result:'邻居进屋搭了把手，你继续自己的安排。'}],after:'村里那户人家已在邻居帮忙下备好晚饭，帮工的人吃完各自回家。'},

 cart:{title:'货车陷泥',place:'road',text:'脚夫正试着把货车推出来。商队愿付8文请人帮忙推车，但这件事与你并没有必然关系。',choices:[{id:'help',label:'帮忙推车',hours:1,energy:12,skill:'carry',xp:1,coins:8,relation:'porter',change:2,result:'你与脚夫合力推车，商队付你8文后继续赶路。阿平记住了你的帮忙。'},{id:'tell',label:'回镇上报信',hours:1,to:'town',result:'镇上的脚行派了人去，剩下的事情由他们处理。'},{id:'leave',label:'不参与',result:'你沿自己的路走，脚夫仍在设法处理。'}],after:'脚行帮忙处理了陷泥的货车，商队继续赶路。'},
 child:{title:'走散的孩子',place:'town',text:'一个孩子在茶摊旁找家人。摊主正在问他住在哪里。',choices:[{id:'help',label:'陪摊主一起找',hours:1,energy:4,relation:'merchant',change:3,result:'你们在粮铺找到孩子的家人。他们道谢后领着孩子回去了。'},{id:'leave',label:'交给摊主，继续自己的事',result:'摊主继续照看孩子，你没有插手。'}],after:'茶摊旁走散的孩子已由街坊送回家。'},
 duel:{title:'两位过路武者争执',place:'bamboo',text:'两人争论一场比试的胜负，语气越来越重。几名行脚人站在远处观望。',choices:[{id:'watch',label:'站远些看一会儿',hours:0.5,energy:2,result:'两人短暂交手后被同伴劝开，各自离去。你看了热闹，没有卷进去。'},{id:'leave',label:'绕路离开',hours:0.25,result:'你绕开争执，不必替陌生人分出高下。'}],after:'竹林里争执的两位武者已被同伴劝开。'},
 herbs:{title:'医者晾药遇雨',place:'village',text:'一阵急雨将至，沈医者正匆忙往屋里收药。',choices:[{id:'help',label:'帮她收药',hours:0.5,energy:4,relation:'doctor',change:3,result:'药材及时收进屋里。沈医者请你坐下避雨。'},{id:'leave',label:'先走自己的路',result:'沈医者喊邻人帮忙，你继续自己的事。'}],after:'河湾村的药材及时收进屋里，没有淋坏。'},
 fair:{title:'临时小集',place:'dock',text:'一艘货船带来了小摊贩。码头有人卖旧器物，也有人只来看热闹。',choices:[{id:'browse',label:'逛一逛，了解行情',hours:1,energy:4,skill:'trade',xp:1,result:'你比较了几家的价钱，记住了常见货物的行情。没有买下任何东西。'},{id:'leave',label:'不逛了',result:'小集还在继续，你有自己的安排。'}],after:'码头的小集散了，船上的商贩去了下一站。'},
 rain:{title:'山道落石',place:'hill',text:'几块碎石挡住了旧道，过路人正在商量清理。',choices:[{id:'help',label:'一起清理',hours:1,energy:12,skill:'carry',xp:1,coins:6,result:'你们把碎石搬到路边，旧道重新可以通行。同行商人凑了6文酬谢你。'},{id:'leave',label:'绕开，不参与',hours:0.5,result:'你从旁边绕过，其他行人继续清理。'}],after:'南山坡的落石已由过路人清理。'},
 dockMeal:{title:'船工的伙食委托',place:'dock',text:'一批船工等着开饭，领工愿付18文请熟悉烹饪的人用自备鲜鱼1、木料1做两份饭食，码头提供灶具。也可以直接交干粮2份，收12文。两条路线任选其一，饭食交给船工，不留在你的背包。',choices:[{id:'cook',label:'现做两份饭食，收18文',requires:{cook:2},input:{fish:1,wood:1},hours:1,energy:8,minHp:25,skill:'cook',xp:2,coins:18,result:'本次制作：鱼饭2份，已交给船工，不进入背包。领工付你18文；灶具留在码头。'},{id:'deliver',label:'交干粮2份，收12文',input:{food:2},hours:0.5,energy:2,skill:'trade',xp:1,coins:12,result:'你交出干粮2份，领工验收后付了12文。没有进行烹饪，因此不增长烹饪经验。'},{id:'leave',label:'不接这份伙食委托',result:'你没有接下委托，领工继续找人准备伙食。'}],after:'码头领工后来请附近饭摊备好伙食，船工吃过饭继续装货。'},
 porterRoof:{title:'阿平准备修屋顶',place:'dock',text:'阿平在码头留了口信，想准备修屋顶的木板。你可以送木料2份，关系增加4，没有工钱或技能经验；若木工Lv2且与阿平关系至少5，也可用自备木料2份加工补板，收16文、关系增加2。他会自己带回家修屋顶，不需要你替他安排生活。',choices:[{id:'supply',label:'送木料2份，帮他备料',input:{wood:2},hours:0.5,energy:2,relation:'porter',change:4,result:'你把木料交到阿平留下的收料处。他记下你的帮助，没有支付工钱；未加工木料，不增长木工经验。'},{id:'prepare',label:'加工补屋顶的木板，收16文',input:{wood:2},requires:{woodwork:2},familiar:{person:'porter',relation:5},hours:1,energy:12,minHp:25,skill:'woodwork',xp:2,coins:16,relation:'porter',change:2,result:'本次完成：补屋顶木板1组，已交付，不进入背包。你加工好木板，收到阿平留下的16文工钱；他会自行带回家补屋顶。'},{id:'leave',label:'不参与阿平的家事',result:'你没有接下这件事，阿平仍会自己找邻人帮忙。'}],after:'阿平已请邻人帮忙备好木板，收工后带回家补了屋顶。'},
 ferryMooring:{title:'贺船工的系泊木桩',place:'ferry',text:'贺船工留了口信，要为搁岸小舟整理系泊处。可帮忙搬齐碎石收8文；若木工Lv2且关系至少5，可自备木料1加工垫木收14文。小舟已搁岸，没有人落水，也不要求你乘船。',choices:[{id:'help',label:'搬齐系泊处碎石，收8文',hours:1,energy:12,minHp:25,skill:'carry',xp:1,coins:8,relation:'boatman',change:2,result:'你把碎石搬齐，贺船工留下的8文工钱交到你手上。小舟仍留在岸边。'},{id:'woodwork',label:'加工系泊垫木，收14文',requires:{woodwork:2},familiar:{person:'boatman',relation:5},input:{wood:1},hours:1,energy:10,minHp:25,skill:'woodwork',xp:1,coins:14,relation:'boatman',change:2,result:'本次完成：系泊垫木1件，已留在系泊处，不进入背包。你收到14文工钱，贺船工会自行装好木桩。'},{id:'leave',label:'不参与，沿岸继续走',result:'你没有接下这份活，贺船工另找邻人整理。'}],after:'贺船工已请邻人整理好系泊处，小舟照常停在旧渡口。'}
};

// 等候只推进游戏时间；与恢复精力的歇息分开。
export const waitingActions={wait30:{name:"等半小时",minutes:30},wait60:{name:"等一小时",minutes:60}};

// 精简版只提供一间可居住旧屋，不模拟地产经营。
export const homePrice=200;
