// 小机会来自固定内容；每个游戏日最多一次非战斗探索偶遇。
export const discoveries={
 herbBasket:{title:'药农的混杂药筐',text:'药农的背筐滑落，采来的普通药草和枯枝混在一起。他愿拿三份草药请熟悉采药的人分拣；也愿付12文请人把药筐搬回河湾村。两种帮忙选一种即可，也可以离开。',choices:[{id:'sort',label:'辨认分拣药草，收草药3份',hours:0.5,energy:8,requires:{herb:2},output:{herb:3},xp:{herb:1},result:'你辨认药草，剔除混杂枯枝。药农按约给你三份普通草药，余下的药筐由他自己带回村。'},{id:'carry',label:'搬药筐回河湾村，收12文',hours:1,energy:12,minHp:25,to:'village',coins:12,xp:{carry:1},result:'你把药筐搬到河湾村，药农付了12文工钱。筐里的草药属于药农，没有进入你的背包。'},{id:'leave',label:'不参与，继续走',result:'你继续沿山坡走，药农留下整理自己的药筐。'}],after:'山坡的药农后来整理好药筐，随另一位村民返回河湾村。'},
 trappedGear:{title:'被落枝压住的猎具',text:'猎户的旧猎具被一根落枝压住。他愿付12文请熟悉林地的人整理枝条；若你有铁制工具和木料，也可帮他垫木拆解，他拿猎物肉2份答谢。没有人或动物受困。',choices:[{id:'clear',label:'辨认枝条、整理落枝，收12文',hours:0.5,energy:8,minHp:25,requires:{forage:2},coins:12,xp:{forage:1},result:'你辨认受力方向，整理出可移开的落枝，猎户取回旧猎具，按约付你12文。'},{id:'lever',label:'用工具和木料垫木拆解，收猎物肉2份',hours:1,energy:10,minHp:25,tool:'tool',input:{wood:1},output:{meat:2},xp:{woodwork:1},result:'你加工垫木，借工具撬起落枝，帮猎户取回猎具。垫木留在现场，工具仍在背包；猎户给你猎物肉2份。'},{id:'leave',label:'不参与，继续走',result:'你继续自己的路，猎户仍在设法取回猎具。'}],after:'竹林猎户后来请路过的樵夫移开落枝，取回猎具回村去了。'},
 herbSale:{title:'赶路商人的草药',text:'一位赶路商人想尽快出发，愿把三份普通草药合计6文卖掉。你可以自己买下，也可以凭经商经验替他联系买家，成交后收12文介绍费。货物普通，没有隐藏品质。',choices:[{id:'buy',label:'花6文买下草药3份',hours:0.25,energy:1,coins:-6,output:{herb:3},result:'你付了6文，收下三份普通草药。商人继续赶路；买来的货物由你自行使用或出售。'},{id:'broker',label:'替他联系买家，收12文介绍费',hours:0.5,energy:4,requires:{trade:2},coins:12,xp:{trade:1},result:'你凭熟悉的行情为商人联系到买家。双方直接成交，你收到12文介绍费，没有把这批草药放进自己的背包。'},{id:'leave',label:'不参与，继续走',result:'你没有接下这笔买卖，商人继续找其他买家。'}],after:'赶路的草药商人后来把货卖给过路药农，收起摊子继续赶路。'},
 oldQuarry:{title:'旧采石棚',text:'山坡转弯处有一座废弃的石棚，里面只有旧采掘痕迹和几块残留矿石。没有机关，也没有藏宝传闻。',choices:[{id:'inspect',label:'查看旧采掘痕迹',hours:1,energy:4,xp:{mining:1},result:'你辨认了敲凿方向和石层。这里是普通的旧作业点，没有发现新的矿脉。'},{id:'extract',label:'用铁制工具敲取残留矿石',hours:1,energy:16,tool:'tool',minHp:25,output:{ore:2},xp:{mining:1},result:'你敲取两份可用铁矿石。工具仍在，石棚没有更多值得冒险开掘的地方。'},{id:'leave',label:'不进去，继续走',result:'你沿山路继续走，没有进入石棚。'}],after:'山坡旧石棚仍在原处；你已记下位置，之后可自行查看剩余作业。'},
 woodcutter:{title:'樵夫的柴捆',text:'一位樵夫正在重新绑散开的柴捆，想请人帮忙搬到林口。他愿意拿6文和两份整理好的木料作酬劳。',choices:[{id:'help',label:'帮忙搬柴到林口',hours:1,energy:12,minHp:25,output:{wood:2},coins:6,xp:{carry:1},result:'你把柴捆搬到林口。樵夫按约给你6文和木料2份，然后自己赶回村里；你仍在竹林。'},{id:'ask',label:'问问林里的道路',hours:0.5,energy:2,result:'樵夫说，土路一头通城外小路，一头通南山坡；雨后泥滑。他继续绑柴，你继续自己的路。'},{id:'leave',label:'不参与，继续走',result:'你没有接下搬柴，樵夫继续整理柴捆。'}],after:'竹林的樵夫后来把柴捆绑牢，自己运回了村里。'},
 herbs:{title:'路边的一小片药草',text:'旧道边有几株常见药草。并不是什么珍稀灵药，采下也需要花些功夫。',choices:[{id:'gather',label:'采两份药草',hours:0.5,energy:8,output:{herb:2},xp:{herb:1},result:'你仔细采下两份常见草药。'},{id:'leave',label:'不采，继续走',result:'你没有动这些药草。'}],after:'旧道边的那片常见药草已被路过的药农采走。'},
 traveler:{title:'扭伤脚的旅人',text:'一位赶路人坐在路边，脚踝肿了。他想回村里找医者，并没有什么惊天秘密。',choices:[{id:'medicine',label:'给他一份草药',hours:0.25,energy:2,input:{herb:1},result:'你把草药交给旅人。他简单处理伤处，慢慢往村里走，没有送你报酬。'},{id:'carry',label:'搀扶他到河湾村',hours:1,energy:12,to:'village',xp:{carry:1},result:'你撑扶旅人走到村口。他去找医者，道谢后与你分别。'},{id:'leave',label:'不参与，继续走',result:'你继续自己的路，旅人向下一位过路人求助。'}],after:'扭伤脚的旅人后来得到村民帮助，已经回到河湾村。'},
 purse:{title:'遗落的小钱袋',text:'泥土上有一只旧钱袋，里面只有3文铜钱。主人可能还会回来找。',choices:[{id:'return',label:'去镇上登记招领',hours:1.5,energy:0,to:'town',result:'你把钱袋交给镇上的值守人，留下招领消息，随后继续自己的生活。'},{id:'take',label:'拿走3文铜钱',hours:0.1,energy:0,coins:3,result:'你取走3文铜钱。这不是一份江湖宝藏，只是别人的零钱。'},{id:'leave',label:'留在原处',result:'你没有动钱袋。'}],after:'遗落的小钱袋被回来寻找的主人领走。'}
};
export function discoveryForRoll(value,place='road'){return value<0.32?'herbs':value<0.42?(place==='hill'?(value<0.37?'oldQuarry':'herbBasket'):place==='bamboo'?(value<0.37?'woodcutter':'trappedGear'):value<0.37?'traveler':'herbSale'):value<0.45?'purse':null}
