import {date,skillLines,items} from './progression.js';
import {areas,npcs} from './world.js';
import {KEY,fresh,restore,note,travel,act,interact,fight} from './engine.js';
let s=null;const $=id=>document.getElementById(id);
function persist(){try{localStorage.setItem(KEY,JSON.stringify(s))}catch{note(s,'本机保存失败，请导出备份。')}render()}
function buttons(id,items,fn){$(id).replaceChildren();for(const [label,value] of items){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{fn(value);persist()};$(id).append(b)}}
function render(){if(!s)return;$('setup').classList.add('hide');$('game').classList.remove('hide');$('hero').textContent=s.name+' · '+s.trade;$('stats').textContent=`气血 ${s.hp}/100 ｜ 精力 ${s.energy}/100 ｜ 饱食 ${s.hunger}/100 ｜ 饮水 ${s.thirst}/100 ｜ 铜钱 ${s.coins}文 ｜ 干粮 ${s.food} ｜ 草药 ${s.herbs} ｜ 拳脚 ${s.skill} ｜ 吐纳 ${s.inner}`;$('profile').textContent=`${s.gender} · ${s.age+Math.floor((s.day-1)/360)}岁 · ${s.personality} · 天赋：${s.talent} · `+Object.entries(s.attributes).map(([k,v])=>k+' '+v).join(' / ');$('skills').textContent=skillLines(s).join(' ｜ ');$('inventory').textContent=Object.entries(items).map(([k,n])=>n+' '+s[k]).join(' ｜ ');$('settlement').replaceChildren();for(const t of s.lastAction){const p=document.createElement('p');p.textContent=t;$('settlement').append(p)}$('place').textContent=s.place;$('desc').textContent=areas[s.place].desc;$('clock').textContent=date(s);
const pairs=x=>x.map(a=>[a,a]);buttons('places',s.combat?[]:pairs(areas[s.place].to),v=>travel(s,v));buttons('actions',s.combat?[]:pairs([...new Set([...areas[s.place].acts,'吃干粮','用草药','用药粉','饮水','休息','睡觉',...(s.learned?['吐纳修炼']:[]),...(npcs(s).some(n=>n.id==='master'&&n.place===s.place)?['切磋']:[])])]),v=>act(s,v));buttons('npcs',s.combat?[]:npcs(s).filter(n=>n.place===s.place).map(n=>[n.name+' · 交谈',n.id]),v=>interact(s,v));$('combat').classList.toggle('hide',!s.combat);$('combat').replaceChildren();if(s.combat){const p=document.createElement('p');p.textContent=s.combat.name+' · 体力 '+s.combat.hp;$('combat').append(p);const box=document.createElement('div');box.id='fight';box.className='actions';$('combat').append(box);buttons('fight',pairs(['出拳',...(s.learned?['运功']:[]),'防守','撤离']),v=>fight(s,v))}$('log').replaceChildren();for(const t of s.log){const p=document.createElement('p');p.textContent=t;$('log').append(p)}}
$('start').onclick=()=>{s=fresh($('name').value,$('trade').value,{age:$('age').value,gender:$('gender').value,personality:$('personality').value,talent:$('talent').value});persist()};$('save').onclick=()=>{if(s){note(s,'已尝试保存本机进度。');persist()}};$('reset').onclick=()=>{if(confirm('确定清除本机进度？请先导出备份。')){try{localStorage.removeItem(KEY)}catch{}s=null;$('setup').classList.remove('hide');$('game').classList.add('hide')}};
$('export').onclick=()=>{if(!s)return;const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='jianghu-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>100000)throw Error('存档文件过大');const next=restore(await f.text());if(s&&!confirm('导入将替换当前进度，是否继续？'))return;s=next;note(s,'存档导入成功。');persist()}catch(err){alert('导入失败：'+err.message)}finally{e.target.value=''}};
try{const raw=localStorage.getItem(KEY);if(raw){s=restore(raw);render()}}catch{alert('本机存档无法读取。可导入备份，或开始新游戏。')}
