import {relationName} from './characters.js?v=0.4.0';
import {dailyMenu} from './simulation.js?v=0.4.0';
import {date,skillLines,items} from './progression.js';
import {areas,npcs} from './world.js?v=0.4.0';
import {KEY,fresh,restore,note,travel,act,interact,fight,chooseEvent,gift,treatment} from './engine.js?v=0.4.0';
let s=null;const $=id=>document.getElementById(id);
function persist(){try{localStorage.setItem(KEY,JSON.stringify(s))}catch{note(s,'本机保存失败，请导出备份。')}render()}
function buttons(id,items,fn){$(id).replaceChildren();for(const [label,value] of items){const b=document.createElement('button');b.textContent=label;b.onclick=()=>{fn(value);persist()};$(id).append(b)}}
function render(){if(!s)return;$('setup').classList.add('hide');$('game').classList.remove('hide');$('hero').textContent=s.name+' · '+s.trade;$('stats').textContent=`气血 ${s.hp}/100 ｜ 精力 ${s.energy}/100 ｜ 铜钱 ${s.coins}文 ｜ 干粮 ${s.food} ｜ 草药 ${s.herbs} ｜ 拳脚 ${s.skill} ｜ 吐纳 ${s.inner}`;$('profile').textContent=`${s.gender} · ${s.age+Math.floor((s.day-1)/360)}岁 · ${s.personality} · 天赋：${s.talent} · `+Object.entries(s.attributes).map(([k,v])=>k+' '+v).join(' / ');$('skills').textContent=skillLines(s).join(' ｜ ');$('inventory').textContent=Object.entries(items).map(([k,n])=>n+' '+s[k]).join(' ｜ ');$('settlement').replaceChildren();for(const t of s.lastAction){const p=document.createElement('p');p.textContent=t;$('settlement').append(p)}$('world').textContent=`天气：${s.world.weather} ｜ 干粮${s.world.grainPrice}文/份 ｜ 粮铺库存${s.world.grainStock}`;for(const [id,lines] of [['news',s.world.news.length?s.world.news:['尚未跨日；世界新闻会在一天结束后生成。']],['daily',dailyMenu(s)]]){$(id).replaceChildren();for(const t of lines){const p=document.createElement('p');p.textContent=t;$(id).append(p)}}$('event').classList.toggle('hide',!s.pendingEvent);$('event').replaceChildren();if(s.pendingEvent){const e=s.world.events.find(e=>e.id===s.pendingEvent);const p=document.createElement('p');p.textContent=e.title+'：脚夫请求协助。你可以参与，也可以离开。';$('event').append(p);const b=document.createElement('div');b.id='choices';b.className='actions';$('event').append(b);buttons('choices',['帮忙推车','去镇上报信','离开'].map(x=>[x,x]),v=>chooseEvent(s,v))}$('place').textContent=s.place;$('desc').textContent=areas[s.place].desc;$('clock').textContent=date(s);
const pairs=x=>x.map(a=>[a,a]);buttons('places',(s.combat||s.pendingEvent)?[]:pairs(areas[s.place].to),v=>travel(s,v));buttons('actions',(s.combat||s.pendingEvent)?[]:pairs([...new Set([...areas[s.place].acts,'吃干粮','用草药','用药粉','休息','睡觉',...(npcs(s).some(n=>n.id==='doctor'&&n.place===s.place)?['请医者治疗']:[]),...(s.learned?['吐纳修炼']:[]),...(npcs(s).some(n=>n.id==='master'&&n.place===s.place)?['切磋']:[])])]),v=>v==='请医者治疗'?treatment(s):act(s,v));buttons('npcs',(s.combat||s.pendingEvent)?[]:npcs(s).filter(n=>n.place===s.place).flatMap(n=>[[n.name+' · 交谈（关系'+(s.relations[n.id]||0)+'/100）',n.id],[n.name+' · 赠礼','gift:'+n.id]]),v=>v.startsWith('gift:')?gift(s,v.slice(5)):interact(s,v));$('npcDetails').replaceChildren();for(const n of npcs(s).filter(n=>n.place===s.place)){const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent=n.name+' · '+relationName(s.relations[n.id]||0);const p=document.createElement('p');p.textContent=`${n.age}岁 · ${n.job} · ${n.personality}。家庭：${n.family}。兴趣：${n.interest}。目标：${n.goal}。能力：${n.ability}。喜欢：${items[n.gift]}。钱财：${n.money}文。`;details.append(summary,p);$('npcDetails').append(details)}$('combat').classList.toggle('hide',!s.combat);$('combat').replaceChildren();if(s.combat){const p=document.createElement('p');p.textContent=s.combat.name+' · 体力 '+s.combat.hp;$('combat').append(p);const box=document.createElement('div');box.id='fight';box.className='actions';$('combat').append(box);buttons('fight',pairs(['出拳',...(s.learned?['运功']:[]),'防守','撤离']),v=>fight(s,v))}$('log').replaceChildren();for(const t of s.log){const p=document.createElement('p');p.textContent=t;$('log').append(p)}}
$('start').onclick=()=>{s=fresh($('name').value,$('trade').value,{age:$('age').value,gender:$('gender').value,personality:$('personality').value,talent:$('talent').value});persist()};$('save').onclick=()=>{if(s){note(s,'已尝试保存本机进度。');persist()}};$('reset').onclick=()=>{if(confirm('确定清除本机进度？请先导出备份。')){try{localStorage.removeItem(KEY)}catch{}s=null;$('setup').classList.remove('hide');$('game').classList.add('hide')}};
$('export').onclick=()=>{if(!s)return;const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='jianghu-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>100000)throw Error('存档文件过大');const next=restore(await f.text());if(s&&!confirm('导入将替换当前进度，是否继续？'))return;s=next;note(s,'存档导入成功。');persist()}catch(err){alert('导入失败：'+err.message)}finally{e.target.value=''}};
try{const raw=localStorage.getItem(KEY);if(raw){s=restore(raw);render()}}catch{alert('本机存档无法读取。可导入备份，或开始新游戏。')}
