import {studyProblem,completeStudy} from './study.js?v=0.6.0';
import {offers} from './trading.js';
import {characters,recordMap} from './characters.js';
import {makeWorld,advanceWorld,validateWorld} from './simulation.js?v=0.6.0';
import {gain,items,recipes,skills,skillCap,canGrow,mastery} from './progression.js?v=0.6.0';
import {areas,npcs} from './world.js?v=0.6.0';
export const KEY='jianghu-single-v01';
export function fresh(name='无名客',trade='农家',profile={}){const s={version:9,talkDays:{},giftDays:{},skillLevels:{},studyDays:{},world:makeWorld(),pendingEvent:null,age:Math.max(16,Math.min(60,Number(profile.age)||18)),gender:['男','女'].includes(profile.gender)?profile.gender:'男',personality:['谨慎','随和','勤奋'].includes(profile.personality)?profile.personality:'谨慎',talent:['均衡','手巧','耐劳'].includes(profile.talent)?profile.talent:'均衡',energy:100,iron:0,wood:0,powder:0,tools:0,fish:0,rod:0,fishing:0,attributes:{力量:5,敏捷:5,根骨:5,悟性:5,幸运:5},carry:0,gather:0,identify:0,medicine:0,forge:0,heat:0,materials:0,cook:0,tradeXP:0,lastAction:[],name:name.trim().slice(0,12)||'无名客',trade,day:1,hour:8,minute:0,place:'青石镇',hp:100,maxHp:100,coins:30,food:2,herbs:0,skill:0,inner:0,learned:false,relations:{},combat:null,log:['你来到青石镇，先谋一口饭吃。']};if(s.talent==='手巧'){s.attributes.敏捷=6;s.attributes.力量=4}if(s.talent==='耐劳'){s.attributes.根骨=6;s.attributes.悟性=4}return s}
export function restore(raw){const a=JSON.parse(raw);if(!a||typeof a.name!=='string'||!areas[a.place]||!Array.isArray(a.log))throw Error('存档格式无效');const s={...fresh(),...a,version:9};for(const k of ['day','hour','hp','maxHp','coins','food','herbs','skill','inner'])if(!Number.isSafeInteger(s[k])||s[k]<0||s[k]>1000000)throw Error('存档数值无效');if(!Number.isInteger(s.minute)||s.minute<0||s.minute>59)throw Error('存档分钟无效');if(s.day<1||s.hour>23||s.maxHp!==100||s.hp<1||s.hp>s.maxHp||!['农家','学徒','行商'].includes(s.trade))throw Error('存档状态无效');if(a.version<3||!a.version){s.skill=Math.min(100,s.skill);s.inner=Math.min(100,s.inner)};if(!s.skillLevels||typeof s.skillLevels!=='object'||Array.isArray(s.skillLevels)||!s.studyDays||typeof s.studyDays!=='object'||Array.isArray(s.studyDays))throw Error('技能阶段存档无效');for(const name of Object.keys(skills)){const level=s.skillLevels[name]??1,day=s.studyDays[name]??1;if(!Number.isInteger(level)||level<1||level>3||!Number.isInteger(day)||day<1||day>s.day)throw Error('技能阶段存档无效')}s.skillLevels=Object.fromEntries(Object.keys(skills).map(n=>[n,s.skillLevels[n]??1]));s.studyDays=Object.fromEntries(Object.keys(skills).map(n=>[n,s.studyDays[n]??1]));if(!Number.isInteger(s.energy)||s.energy<0||s.energy>100)throw Error('精力存档无效');for(const [n,k] of Object.entries(skills))if(!Number.isInteger(s[k])||s[k]<0||s[k]>skillCap(s,n))throw Error('技能存档无效');for(const k of ['iron','wood','powder','tools','fish','rod'])if(!Number.isSafeInteger(s[k])||s[k]<0||s[k]>1000000)throw Error('库存无效');if(!Number.isInteger(s.age)||s.age<16||s.age>60||!['男','女'].includes(s.gender)||!['谨慎','随和','勤奋'].includes(s.personality)||!['均衡','手巧','耐劳'].includes(s.talent))throw Error('人物资料无效');s.attributes=fresh('无名客',s.trade,{talent:s.talent}).attributes;s.world=a.world?validateWorld(a.world,s.day):makeWorld(s.day);s.pendingEvent=typeof a.pendingEvent==='string'&&s.world.events.some(e=>e.id===a.pendingEvent&&e.status==='open'&&e.place===s.place)?a.pendingEvent:null;delete s.hunger;delete s.thirst;s.lastAction=[];s.name=s.name.slice(0,12);s.log=s.log.filter(x=>typeof x==='string').slice(0,35);s.relations=Object.fromEntries(Object.keys(characters).map(k=>[k,Number.isSafeInteger(s.relations?.[k])?Math.max(0,Math.min(100,s.relations[k])):0]));s.talkDays=recordMap(a.talkDays);s.giftDays=recordMap(a.giftDays);s.learned=s.learned===true;if(s.combat){const c=s.combat;if(!['山贼','周师傅'].includes(c.name)||!Number.isInteger(c.hp)||c.hp<1||c.hp>60||!Number.isInteger(c.attack)||c.attack<1||c.attack>10||typeof c.spar!=='boolean')throw Error('战斗存档无效');s.combat={name:c.name,hp:c.hp,attack:c.attack,spar:c.name==='周师傅'};}return s}
export function note(s,t){s.log.unshift(`第${s.day}日 · ${t}`);s.log=s.log.slice(0,35)}
export function tick(s,h=1){const total=s.hour*60+(s.minute||0)+Math.round(h*60);s.day+=Math.floor(total/1440);s.hour=Math.floor(total%1440/60);s.minute=total%60;advanceWorld(s)}
function base_travel(s,to){if(s.combat||!areas[s.place].to.includes(to))return false;tick(s,s.world.weather==='雨'&&['城外小路','竹林','山坡','河边'].includes(to)?2:1);s.place=to;note(s,`抵达${to}。`);return true}
function base_interact(s,id){if(s.combat)return;const n=npcs(s).find(n=>n.id===id&&n.place===s.place);if(!n)return;note(s,`${n.name}：${n.text}`);if(s.talkDays[id]!==s.day){const before=s.relations[id]||0;const bonus=n.personality===s.personality?2:1;s.relations[id]=Math.min(100,before+bonus);s.talkDays[id]=s.day;note(s,`${n.name}关系：${before}/100 → ${s.relations[id]}/100（+${s.relations[id]-before}）`)}else note(s,'今日已交谈过，重复交谈不再增加关系。');if(id==='master'&&!s.learned){s.learned=true;note(s,'周师傅教你基础吐纳，可自行修炼。')}tick(s)}
function base_act(s,a,rng=Math.random){if(s.combat)return;if(![...areas[s.place].acts,'休息','吃干粮','用草药','吐纳修炼','切磋'].includes(a))return;switch(a){
case '打零工':tick(s,3);s.coins+=12;note(s,'搬运货物，赚得12文。');break;
case '休息':tick(s,2);s.hp=Math.min(100,s.hp+25);note(s,'歇息恢复气血与精力，恢复量见结算。');break;
case '买干粮':if(!npcs(s).some(n=>n.id==='merchant'&&n.place===s.place)){note(s,'粮铺已打烊。');break}if(s.world.grainStock<1){note(s,'粮铺今日库存不足，等待补货。');break}if(s.coins<s.world.grainPrice){note(s,'铜钱不足。');break}s.coins-=s.world.grainPrice;s.world.npcMoney.merchant+=s.world.grainPrice;s.world.grainStock--;s.food++;tick(s);break;
case '卖干粮':if(!npcs(s).some(n=>n.id==='merchant'&&n.place===s.place)){note(s,'粮铺已打烊。');break}if(!s.food){note(s,'没有干粮。');break}if(s.world.npcMoney.merchant<3){note(s,'掌柜钱财不足，暂不收购。');break}s.food--;s.coins+=3;s.world.npcMoney.merchant-=3;s.world.grainStock=Math.min(60,s.world.grainStock+1);tick(s);break;
case '住店':if(s.coins<8){note(s,'住店需要8文。');break}s.coins-=8;s.hp=100;tick(s,8);note(s,'住店休养，体力恢复。');break;
case '练习拳脚':if(s.hp<=12){note(s,'体力不足，请休息。');break}s.skill=Math.min(skillCap(s,'拳脚'),s.skill+2);tick(s,2);note(s,'完成拳脚练习。');break;
case '吐纳修炼':if(!s.learned){note(s,'先向周师傅请教。');break}tick(s,2);s.inner=Math.min(skillCap(s,'吐纳'),s.inner+2);s.hp=Math.min(100,s.hp+10);note(s,'完成吐纳练习。');break;
case '吃干粮':case '用草药':{const k=a==='吃干粮'?'food':'herbs';if(!s[k]){note(s,'没有可用物品。');break}if(s.hp===100&&(k==='herbs'||s.energy===100)){note(s,'当前无需恢复，不消耗物品。');break}s[k]--;s.hp=Math.min(100,s.hp+(k==='food'?20:30));tick(s);note(s,'使用物品恢复体力。');break}
case '采集草药':tick(s,2);if(rng()<(s.energy<20?0.4:0.6)+mastery(s,'采药')/1000){s.herbs++;note(s,'采到一株草药。')}else note(s,'此次没有收获。');break;
case '探路':tick(s);if(rng()<0.45){s.combat={name:'山贼',hp:35,attack:7,spar:false};note(s,'遇到拦路山贼，可战斗或撤离。')}else note(s,'你记下沿途地势，平安走过。');break;
case '切磋':if(!npcs(s).some(n=>n.id==='master'&&n.place===s.place))return;s.combat={name:'周师傅',hp:45,attack:5,spar:true};note(s,'周师傅答应点到为止。');break;
default:if(a==='与掌柜交谈')base_interact(s,'merchant');else{tick(s);note(s,'旅人说：周师傅白日在城外教拳，夜里回客栈歇息。')}
}}
function base_fight(s,a){
const c=s.combat;if(!c||!['出拳','运功','防守','撤离'].includes(a))return;
if(a==='运功'&&!s.learned){note(s,'尚未学会吐纳。');return}
if(a==='撤离'){s.combat=null;tick(s,1/60);note(s,'你脱身离开，不必逞强。');return}
const guard=a==='防守',fatigue=s.energy<10?0.5:s.energy<20?0.75:1;
if(!guard){c.hp-=Math.max(1,Math.floor((8+Math.floor(mastery(s,'拳脚')/25)+(a==='运功'?3+Math.floor(mastery(s,'吐纳')/25):0))*fatigue));s.skill=Math.min(skillCap(s,'拳脚'),s.skill+1);if(a==='运功')s.inner=Math.min(skillCap(s,'吐纳'),s.inner+1)}
tick(s,1/60);
if(c.hp<=0){if(!c.spar)s.coins+=10;s.combat=null;note(s,c.spar?'切磋获胜。':'击退山贼，获得10文。');return}
s.hp=Math.max(0,s.hp-Math.max(1,c.attack-(guard?4:0)-Math.floor(mastery(s,'吐纳')/40)));note(s,`你${a}，${c.name}还击。`);
if(s.hp<=0){s.combat=null;s.hp=35;s.place='客栈';s.coins=Math.max(0,s.coins-5);tick(s,4);note(s,'你失去战力，被路人送回客栈，花去至多5文养伤。')}
}
const costs={'打零工':24,'练习拳脚':18,'吐纳修炼':8,'采集草药':16,'探路':10,'买干粮':2,'卖干粮':2,'打听消息':3,'住店':0,'休息':0,'吃干粮':0,'用草药':0,'切磋':0};
const related={'打零工':['搬运'],'采集草药':['采药'],'卖干粮':['经商']};
function settle(s,label,cost,run,extraSkills=[]){const before=structuredClone(s);s.lastAction=[];if(label==='战斗·撤离')cost=Math.min(cost,s.energy);if(cost>s.energy){s.lastAction=['精力不足，请先休息或睡觉。'];return false}const learningEnergy=Math.max(0,s.energy-cost);const efficiency=learningEnergy<10?0.25:learningEnergy<20?0.5:1;run();const changed=JSON.stringify({...s,lastAction:[]})!==JSON.stringify({...before,lastAction:[]});if(!changed){s.lastAction=['当前行动不可执行。'];return false}const advanced=s.day!==before.day||s.hour!==before.hour||s.minute!==before.minute;const active=advanced||JSON.stringify(s.combat)!==JSON.stringify(before.combat)||(label.startsWith('战斗')&&s.hp!==before.hp);if(active){s.energy=Math.max(0,s.energy-cost);for(const [name,key] of [['拳脚','skill'],['吐纳','inner']]){const amount=s[key]-before[key];if(amount>0){s[key]=before[key];s.lastAction.push(gain(s,name,Math.max(1,amount*efficiency)))}}for(const name of extraSkills){const key=skills[name];if(canGrow(s,name))s.lastAction.push(gain(s,name,Math.max(1,2*efficiency)))}if(label==='采集草药'&&s.herbs>before.herbs&&canGrow(s,'药材辨识'))s.lastAction.push(gain(s,'药材辨识',Math.max(1,2*efficiency)));}s.lastAction.unshift(label,`精力：${before.energy} → ${s.energy}（${s.energy-before.energy>=0?'+':''}${s.energy-before.energy}）`,`金钱：${before.coins} → ${s.coins}（${s.coins-before.coins>=0?'+':''}${s.coins-before.coins}文）`);if(s.hp!==before.hp)s.lastAction.push(`气血：${before.hp} → ${s.hp}（${s.hp-before.hp>=0?'+':''}${s.hp-before.hp}）`);if(recipes[label]&&active){const r=recipes[label];s.lastAction.push('材料消耗：'+Object.entries(r.input).map(([k,n])=>`${items[k]} -${n}`).join('、'),'当前库存：'+[...new Set([...Object.keys(r.input),...Object.keys(r.output)])].map(k=>`${items[k]} ${s[k]}`).join('、'))}for(const [k,n] of Object.entries(items)){if(s[k]!==before[k])s.lastAction.push(`${n}：${before[k]} → ${s[k]}（${s[k]-before[k]>=0?'+':''}${s[k]-before[k]}）`)}if(s.energy<20)s.lastAction.push(s.energy<10?'极疲：训练和生产效率下降。':'疲惫：训练和生产效率下降。');for(const line of s.lastAction)note(s,line);if(!s.combat&&!s.pendingEvent){const event=s.world.events.find(e=>e.status==='open'&&e.place===s.place);if(event)s.pendingEvent=event.id}return active}
export function travel(s,to){if(s.pendingEvent){s.lastAction=['先选择如何处理眼前事件，可以直接离开。'];return false}return settle(s,`前往${to}`,0,()=>base_travel(s,to))}
export function interact(s,id){if(s.pendingEvent)return false;return settle(s,'交谈',2,()=>base_interact(s,id))}
export function act(s,a,rng=Math.random){if(s.combat||s.pendingEvent)return;if(a.startsWith('进修：')){const name=a.slice(3),problem=studyProblem(s,name);if(problem){s.lastAction=[problem];return false}return settle(s,a,12,()=>{tick(s,4);s.lastAction.push(completeStudy(s,name))})}const offer=offers[a];if(offer){const buyer=npcs(s).find(n=>n.id===offer.buyer&&n.place===s.place);if(s.place!==offer.place||!buyer){s.lastAction=['收购者不在此地，请在白日营业时前来。'];return}if(s[offer.item]<1){s.lastAction=[`没有可出售的${items[offer.item]}。`];return}if(s.world.npcMoney[offer.buyer]<offer.price){s.lastAction=[`${buyer.name}钱财不足，暂时无法收购。`];return}return settle(s,a,2,()=>{s[offer.item]--;s.coins+=offer.price;s.world.npcMoney[offer.buyer]-=offer.price;tick(s);note(s,`向${buyer.name}出售${items[offer.item]}×1，获得${offer.price}文。`)},['经商'])}
if(a==='钓鱼'){if(s.place!=='河边'){s.lastAction=['请前往河边钓鱼。'];return}if(s.rod<1){s.lastAction=['需要钓竿，可在作坊花6文购买。'];return}return settle(s,a,16,()=>{const chance=(s.energy<20?0.4:0.65)+mastery(s,'钓鱼')/1000;tick(s,2);if(rng()<chance){s.fish++;note(s,'本次收获：鲜鱼×1。')}else note(s,'守候两小时，没有钓到鱼。')},['钓鱼'])}
if(a==='买钓竿'){if(s.place!=='作坊'||s.hour<7||s.hour>=19){s.lastAction=['请在07:00–19:00到作坊购买。'];return}if(s.coins<6){s.lastAction=['钓竿需要6文。'];return}return settle(s,a,2,()=>{s.coins-=6;s.rod++;tick(s)})}
const recipe=recipes[a];if(recipe){if(s.place!=='作坊'){s.lastAction=['请前往作坊生产。'];return}for(const [k,n] of Object.entries(recipe.input))if(s[k]<n){s.lastAction=[`${items[k]}不足，需要${n}，库存${s[k]}。`];return}return settle(s,a,recipe.energy,()=>{for(const [k,n] of Object.entries(recipe.input))s[k]-=n;tick(s,recipe.hours);const fail=s.energy-recipe.energy<20&&rng()<0.2;if(!fail)for(const [k,n] of Object.entries(recipe.output))s[k]+=n;note(s,fail?'疲劳造成生产失误，材料已消耗，未产出。':`本次生产：${Object.entries(recipe.output).map(([k,n])=>items[k]+'×'+n).join('、')}`)},recipe.skills)}
if(a==='买铁料'||a==='买木料'){if(s.place!=='作坊'||s.hour<7||s.hour>=19){s.lastAction=['作坊材料柜营业时间为07:00–19:00。'];return}const k=a==='买铁料'?'iron':'wood',price=k==='iron'?6:2;if(s.coins<price){s.lastAction=['铜钱不足。'];return}return settle(s,a,2,()=>{s.coins-=price;s[k]++;tick(s)})}
if(a==='睡觉'||a==='用药粉'){if(a==='用药粉'&&!s.powder){s.lastAction=['没有药粉。'];return}if(a==='用药粉'&&s.hp===100){s.lastAction=['气血充足，无需使用药粉。'];return}if(a==='睡觉'&&!['客栈','河湾村'].includes(s.place)){s.lastAction=['请到客栈住店，或到河湾村借宿睡觉。'];return}if(a==='睡觉'&&s.place==='客栈'&&s.coins<8){s.lastAction=['住店需要8文。'];return}return settle(s,a,0,()=>{if(a==='睡觉'){if(s.place==='客栈')s.coins-=8;tick(s,8);s.energy=100;s.hp=Math.min(100,s.hp+25)}else{s.powder--;tick(s);s.hp=Math.min(100,s.hp+35)}})}
return settle(s,a,costs[a]||0,()=>{const hour=s.day*24+s.hour;base_act(s,a,rng);if(s.day*24+s.hour!==hour){if(a==='休息')s.energy=Math.min(100,s.energy+30);if(a==='住店')s.energy=100;if(a==='吃干粮'){s.energy=Math.min(100,s.energy+10)}}},related[a]||[])}
export function fight(s,a){return settle(s,`战斗·${a}`,a==='撤离'?3:4,()=>base_fight(s,a))}

export function chooseEvent(s,choice){if(!['帮忙推车','去镇上报信','离开'].includes(choice))return false;const e=s.world.events.find(e=>e.id===s.pendingEvent&&e.status==='open');if(!e){s.pendingEvent=null;return false}if(choice==='帮忙推车'&&s.energy<16){s.lastAction=['精力不足，可报信或离开。'];return false}return settle(s,choice,choice==='帮忙推车'?16:0,()=>{s.pendingEvent=null;if(choice==='帮忙推车'){e.status='helped';s.relations.porter=Math.min(100,(s.relations.porter||0)+2);tick(s,2);note(s,'你协助脚夫搬运，货车重新上路；阿平关系+2。')}else if(choice==='去镇上报信'){e.status='resolved';s.place='青石镇';tick(s);note(s,'你通知镇上脚行，货车由脚夫处理。')}else{e.status='ignored';note(s,'你没有参与；脚夫会自行处理。')}} ,choice==='帮忙推车'?['搬运']:[])}

export function gift(s,id){if(s.combat||s.pendingEvent)return false;const n=npcs(s).find(n=>n.id===id&&n.place===s.place);if(!n)return false;if(s.giftDays[id]===s.day){s.lastAction=['今日已赠礼，请改日再来。'];return false}if(s[n.gift]<1){s.lastAction=[`${n.name}喜欢${items[n.gift]}，你目前没有。`];return false}return settle(s,`赠礼给${n.name}`,2,()=>{s[n.gift]--;s.giftDays[id]=s.day;const before=s.relations[id]||0;s.relations[id]=Math.min(100,before+n.giftGain);tick(s);note(s,`${n.name}收下${items[n.gift]}。关系：${before}/100 → ${s.relations[id]}/100（+${s.relations[id]-before}）`)})}
export function treatment(s){if(s.combat||s.pendingEvent)return false;if(!npcs(s).some(n=>n.id==='doctor'&&n.place===s.place)){s.lastAction=['沈医者不在此地。'];return false}if(s.hp===100){s.lastAction=['气血充足，无需治疗。'];return false}if(s.coins<6){s.lastAction=['治疗需要6文。'];return false}return settle(s,'沈医者治疗',0,()=>{const before=s.hp;s.coins-=6;s.world.npcMoney.doctor+=6;s.hp=Math.min(100,s.hp+50);tick(s,2);note(s,`沈医者为你处理外伤，气血：${before} → ${s.hp}（+${s.hp-before}）`)})}
