import {gain,items,recipes} from './progression.js';
import {areas,npcs} from './world.js';
export const KEY='jianghu-single-v01';
export function fresh(name='无名客',trade='农家',profile={}){const s={version:3,age:Math.max(16,Math.min(60,Number(profile.age)||18)),gender:['男','女'].includes(profile.gender)?profile.gender:'男',personality:['谨慎','随和','勤奋'].includes(profile.personality)?profile.personality:'谨慎',talent:['均衡','手巧','耐劳'].includes(profile.talent)?profile.talent:'均衡',energy:100,hunger:100,thirst:100,iron:0,wood:0,powder:0,tools:0,attributes:{力量:5,敏捷:5,根骨:5,悟性:5,幸运:5},carry:0,gather:0,identify:0,medicine:0,forge:0,heat:0,materials:0,cook:0,tradeXP:0,lastAction:[],name:name.trim().slice(0,12)||'无名客',trade,day:1,hour:8,place:'青石镇',hp:100,maxHp:100,coins:30,food:2,herbs:0,skill:0,inner:0,learned:false,relations:{},combat:null,log:['你来到青石镇，先谋一口饭吃。']};if(s.talent==='手巧'){s.attributes.敏捷=6;s.attributes.力量=4}if(s.talent==='耐劳'){s.attributes.根骨=6;s.attributes.悟性=4}return s}
export function restore(raw){const a=JSON.parse(raw);if(!a||typeof a.name!=='string'||!areas[a.place]||!Array.isArray(a.log))throw Error('存档格式无效');const s={...fresh(),...a,version:3};for(const k of ['day','hour','hp','maxHp','coins','food','herbs','skill','inner'])if(!Number.isSafeInteger(s[k])||s[k]<0||s[k]>1000000)throw Error('存档数值无效');if(s.day<1||s.hour>23||s.maxHp!==100||s.hp<1||s.hp>s.maxHp||!['农家','学徒','行商'].includes(s.trade))throw Error('存档状态无效');if(a.version<3||!a.version){s.skill=Math.min(100,s.skill);s.inner=Math.min(100,s.inner)};for(const k of ['energy','hunger','thirst','skill','inner','carry','gather','identify','medicine','forge','heat','materials','cook','tradeXP'])if(!Number.isInteger(s[k])||s[k]<0||s[k]>100)throw Error('精力或技能存档无效');for(const k of ['iron','wood','powder','tools'])if(!Number.isSafeInteger(s[k])||s[k]<0||s[k]>1000000)throw Error('库存无效');if(!Number.isInteger(s.age)||s.age<16||s.age>60||!['男','女'].includes(s.gender)||!['谨慎','随和','勤奋'].includes(s.personality)||!['均衡','手巧','耐劳'].includes(s.talent))throw Error('人物资料无效');s.attributes=fresh('无名客',s.trade,{talent:s.talent}).attributes;s.lastAction=[];s.name=s.name.slice(0,12);s.log=s.log.filter(x=>typeof x==='string').slice(0,35);s.relations=Object.fromEntries(['master','merchant','porter'].map(k=>[k,Number.isSafeInteger(s.relations?.[k])?Math.max(0,Math.min(100,s.relations[k])):0]));s.learned=s.learned===true;if(s.combat){const c=s.combat;if(!['山贼','周师傅'].includes(c.name)||!Number.isInteger(c.hp)||c.hp<1||c.hp>60||!Number.isInteger(c.attack)||c.attack<1||c.attack>10||typeof c.spar!=='boolean')throw Error('战斗存档无效');s.combat={name:c.name,hp:c.hp,attack:c.attack,spar:c.name==='周师傅'};}return s}
export function note(s,t){s.log.unshift(`第${s.day}日 · ${t}`);s.log=s.log.slice(0,35)}
export function tick(s,h=1){s.hunger=Math.max(0,s.hunger-h);s.thirst=Math.max(0,s.thirst-2*h);s.hour+=h;while(s.hour>=24){s.hour-=24;s.day++}}
function base_travel(s,to){if(s.combat||!areas[s.place].to.includes(to))return false;tick(s);s.place=to;note(s,`抵达${to}。`);return true}
function base_interact(s,id){if(s.combat)return;const n=npcs(s).find(n=>n.id===id&&n.place===s.place);if(!n)return;note(s,`${n.name}：${n.text}`);s.relations[id]=Math.min(100,(s.relations[id]||0)+1);if(id==='master'&&!s.learned){s.learned=true;note(s,'周师傅教你基础吐纳，可自行修炼。')}tick(s)}
function base_act(s,a,rng=Math.random){if(s.combat)return;if(![...areas[s.place].acts,'休息','吃干粮','用草药','吐纳修炼','切磋'].includes(a))return;switch(a){
case '打零工':tick(s,3);s.coins+=12;note(s,'搬运货物，赚得12文。');break;
case '休息':tick(s,2);s.hp=Math.min(100,s.hp+25);note(s,'歇息恢复25点体力。');break;
case '买干粮':if(!npcs(s).some(n=>n.id==='merchant'&&n.place===s.place)){note(s,'粮铺已打烊。');break}if(s.coins<5){note(s,'铜钱不足。');break}s.coins-=5;s.food++;tick(s);break;
case '卖干粮':if(!npcs(s).some(n=>n.id==='merchant'&&n.place===s.place)){note(s,'粮铺已打烊。');break}if(!s.food){note(s,'没有干粮。');break}s.food--;s.coins+=3;tick(s);break;
case '住店':if(s.coins<8){note(s,'住店需要8文。');break}s.coins-=8;s.hp=100;tick(s,8);note(s,'住店休养，体力恢复。');break;
case '练习拳脚':if(s.hp<=12){note(s,'体力不足，请休息。');break}s.skill=Math.min(100,s.skill+2);tick(s,2);note(s,'完成拳脚练习。');break;
case '吐纳修炼':if(!s.learned){note(s,'先向周师傅请教。');break}tick(s,2);s.inner=Math.min(100,s.inner+2);s.hp=Math.min(100,s.hp+10);note(s,'完成吐纳练习。');break;
case '吃干粮':case '用草药':{const k=a==='吃干粮'?'food':'herbs';if(!s[k]){note(s,'没有可用物品。');break}s[k]--;s.hp=Math.min(100,s.hp+(k==='food'?20:30));tick(s);note(s,'使用物品恢复体力。');break}
case '采集草药':tick(s,2);if(rng()<0.6){s.herbs++;note(s,'采到一株草药。')}else note(s,'此次没有收获。');break;
case '探路':tick(s);if(rng()<0.45){s.combat={name:'山贼',hp:35,attack:7,spar:false};note(s,'遇到拦路山贼，可战斗或撤离。')}else note(s,'你记下沿途地势，平安走过。');break;
case '切磋':if(!npcs(s).some(n=>n.id==='master'&&n.place===s.place))return;s.combat={name:'周师傅',hp:45,attack:5,spar:true};note(s,'周师傅答应点到为止。');break;
default:if(a==='与掌柜交谈')base_interact(s,'merchant');else{tick(s);note(s,'旅人说：周师傅白日在城外教拳，夜里回客栈歇息。')}
}}
function base_fight(s,a){const c=s.combat;if(!c||!['出拳','运功','防守','撤离'].includes(a))return;if(a==='撤离'){s.combat=null;tick(s);note(s,'你脱身离开，不必逞强。');return}let guard=a==='防守';if(a==='运功'&&!s.learned){note(s,'尚未学会吐纳。');return}if(!guard)c.hp-=8+Math.floor(s.skill/25)+(a==='运功'?3+Math.floor(s.inner/25):0);if(c.hp<=0){s.skill=Math.min(100,s.skill+3);if(!c.spar)s.coins+=10;s.combat=null;tick(s);note(s,c.spar?'切磋获胜。':'击退山贼，获得10文。');return}s.hp=Math.max(0,s.hp-Math.max(1,c.attack-(guard?4:0)-Math.floor(s.inner/40)));note(s,`你${a}，${c.name}还击。`);if(s.hp<=0){s.combat=null;s.hp=35;s.place='客栈';s.coins=Math.max(0,s.coins-5);tick(s,4);note(s,'你失去战力，被路人送回客栈，花去至多5文养伤。')}}
const costs={'打零工':24,'练习拳脚':18,'吐纳修炼':8,'采集草药':16,'探路':10,'买干粮':2,'卖干粮':2,'打听消息':3,'住店':0,'休息':0,'吃干粮':0,'用草药':0,'切磋':0};
const related={'打零工':['搬运'],'采集草药':['采药','药材辨识'],'买干粮':['经商'],'卖干粮':['经商']};
function settle(s,label,cost,run,extraSkills=[]){const before=structuredClone(s);s.lastAction=[];if((s.hunger===0||s.thirst===0)&&cost>0)cost+=2;if(label==='战斗·撤离')cost=Math.min(cost,s.energy);if(cost>s.energy){s.lastAction=['精力不足，请先休息或睡觉。'];return false}const efficiency=s.energy<10?0.25:s.energy<20?0.5:1;run();const changed=JSON.stringify({...s,lastAction:[]})!==JSON.stringify({...before,lastAction:[]});if(!changed){s.lastAction=['当前行动不可执行。'];return false}const advanced=s.day!==before.day||s.hour!==before.hour;const active=advanced||JSON.stringify(s.combat)!==JSON.stringify(before.combat)||(label.startsWith('战斗')&&s.hp!==before.hp);if(active){s.energy=Math.max(0,s.energy-cost);for(const [name,key] of [['拳脚','skill'],['吐纳','inner']]){const amount=s[key]-before[key];if(amount>0){s[key]=before[key];s.lastAction.push(gain(s,name,Math.max(1,amount*efficiency)))}}for(const name of extraSkills)s.lastAction.push(gain(s,name,Math.max(1,2*efficiency)));}s.lastAction.unshift(label,`精力：${before.energy} → ${s.energy}（${s.energy-before.energy>=0?'+':''}${s.energy-before.energy}）`,`金钱：${before.coins} → ${s.coins}（${s.coins-before.coins>=0?'+':''}${s.coins-before.coins}文）`);for(const [k,n] of Object.entries(items)){if(s[k]!==before[k])s.lastAction.push(`${n}：${before[k]} → ${s[k]}（${s[k]-before[k]>=0?'+':''}${s[k]-before[k]}）`)}if(s.energy<20)s.lastAction.push(s.energy<10?'极疲：训练和生产效率下降。':'疲惫：训练和生产效率下降。');for(const line of s.lastAction)note(s,line);if(s.hunger<20||s.thirst<20)s.lastAction.push('饥渴：请及时进食饮水；耗尽时劳作精力消耗增加。');return active}
export function travel(s,to){return settle(s,`前往${to}`,0,()=>base_travel(s,to))}
export function interact(s,id){return settle(s,'交谈',2,()=>base_interact(s,id))}
export function act(s,a,rng=Math.random){if(s.combat)return;const recipe=recipes[a];if(recipe){if(s.place!=='作坊'){s.lastAction=['请前往作坊生产。'];return}for(const [k,n] of Object.entries(recipe.input))if(s[k]<n){s.lastAction=[`${items[k]}不足，需要${n}，库存${s[k]}。`];return}return settle(s,a,recipe.energy,()=>{for(const [k,n] of Object.entries(recipe.input))s[k]-=n;tick(s,recipe.hours);const fail=s.energy<20&&rng()<0.2;if(!fail)for(const [k,n] of Object.entries(recipe.output))s[k]+=n;note(s,fail?'疲劳造成生产失误，材料已消耗，未产出。':`本次生产：${Object.entries(recipe.output).map(([k,n])=>items[k]+'×'+n).join('、')}`)},recipe.skills)}
if(a==='买铁料'||a==='买木料'){if(s.place!=='作坊'||s.hour<7||s.hour>=19){s.lastAction=['作坊材料柜营业时间为07:00–19:00。'];return}const k=a==='买铁料'?'iron':'wood',price=k==='iron'?6:2;if(s.coins<price){s.lastAction=['铜钱不足。'];return}return settle(s,a,2,()=>{s.coins-=price;s[k]++;tick(s)},['经商'])}
if(a==='饮水'||a==='睡觉'||a==='用药粉'){if(a==='用药粉'&&!s.powder){s.lastAction=['没有药粉。'];return}if(a==='睡觉'&&!['客栈','河湾村'].includes(s.place)){s.lastAction=['请到客栈住店，或到河湾村借宿睡觉。'];return}if(a==='睡觉'&&s.place==='客栈'&&s.coins<8){s.lastAction=['住店需要8文。'];return}return settle(s,a,0,()=>{if(a==='饮水'){tick(s);s.thirst=100}else if(a==='睡觉'){if(s.place==='客栈')s.coins-=8;tick(s,8);s.energy=100;s.hp=Math.min(100,s.hp+25)}else{s.powder--;tick(s);s.hp=Math.min(100,s.hp+35)}})}
return settle(s,a,costs[a]||0,()=>{const hour=s.day*24+s.hour;base_act(s,a,rng);if(s.day*24+s.hour!==hour){if(a==='休息')s.energy=Math.min(100,s.energy+30);if(a==='住店')s.energy=100;if(a==='吃干粮'){s.energy=Math.min(100,s.energy+10);s.hunger=Math.min(100,s.hunger+35)}}},related[a]||[])}
export function fight(s,a){return settle(s,`战斗·${a}`,a==='撤离'?3:4,()=>base_fight(s,a))}
